(()=>{"use strict";
const D=window.ASTRORIUM_DATA||{constellations:[],stars:[],dsos:[],planetsInfo:[],asterisms:[],solarSystem:[]};
const ART=window.ASTRORIUM_CONSTELLATION_ART||{}, ART_IMAGES={}, ART_MESH_CACHE={};
const ART_LAYER_CACHE={canvas:null,ctx:null,lastDraw:0,lastStructure:"",lastMotion:"",mode:"direct",scale:1,interval:0};let ART_CONFIG_REV=0;
const R=Math.PI/180, clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), norm=v=>((v%360)+360)%360;
const C=Object.fromEntries(D.constellations.map(x=>[x.id,x]));
const S=Object.fromEntries(D.stars.map(x=>[x.id,x]));
const O=Object.fromEntries(D.dsos.map(x=>[x.id,x]));
const PINFO=Object.fromEntries((D.planetsInfo||[]).map(x=>[x.id,x]));
const SOLAR=Object.fromEntries((D.solarSystem||[]).map(x=>[x.id,x]));
const AU_KM=149597870.7;
const EXTRA={
 Dubhe:{id:"Dubhe",name:"ドゥーベ",ra:165.932,dec:61.751,mag:1.79},Merak:{id:"Merak",name:"メラク",ra:165.4603,dec:56.3824,mag:2.37},Phecda:{id:"Phecda",name:"フェクダ",ra:178.4577,dec:53.6948,mag:2.44},Megrez:{id:"Megrez",name:"メグレズ",ra:183.8565,dec:57.0326,mag:3.31},Alioth:{id:"Alioth",name:"アリオト",ra:193.5073,dec:55.9598,mag:1.76},Alkaid:{id:"Alkaid",name:"アルカイド",ra:206.8852,dec:49.3133,mag:1.85},
 Bellatrix:{id:"Bellatrix",name:"ベラトリックス",ra:81.2828,dec:6.3497,mag:1.64},Alnitak:{id:"Alnitak",name:"アルニタク",ra:85.1897,dec:-1.9426,mag:1.74},Alnilam:{id:"Alnilam",name:"アルニラム",ra:84.0534,dec:-1.2019,mag:1.69},Mintaka:{id:"Mintaka",name:"ミンタカ",ra:83.0017,dec:-0.2991,mag:2.25},Saiph:{id:"Saiph",name:"サイフ",ra:86.9391,dec:-9.6696,mag:2.06},
 Denebola:{id:"Denebola",name:"デネボラ",ra:177.2649,dec:14.5721,mag:2.14},Algieba:{id:"Algieba",name:"アルギエバ",ra:154.9931,dec:19.8415,mag:2.08},Zosma:{id:"Zosma",name:"ゾスマ",ra:168.5271,dec:20.5237,mag:2.56},
 Shaula:{id:"Shaula",name:"シャウラ",ra:263.4022,dec:-37.1038,mag:1.62},Sargas:{id:"Sargas",name:"サルガス",ra:264.3297,dec:-42.9978,mag:1.86},Dschubba:{id:"Dschubba",name:"ジュバ",ra:240.0834,dec:-22.6217,mag:2.32},Acrab:{id:"Acrab",name:"アクラブ",ra:241.3593,dec:-19.8055,mag:2.62},
 KausAust:{id:"KausAust",name:"カウス・アウストラリス",ra:283.8164,dec:-34.3846,mag:1.79},Nunki:{id:"Nunki",name:"ヌンキ",ra:283.5424,dec:-26.2967,mag:2.05},Ascella:{id:"Ascella",name:"アスケラ",ra:285.653,dec:-29.8801,mag:2.6},
 Alpheratz:{id:"Alpheratz",name:"アルフェラッツ",ra:2.0969,dec:29.0904,mag:2.06},Mirach:{id:"Mirach",name:"ミラク",ra:17.433,dec:35.6206,mag:2.05},Markab:{id:"Markab",name:"マルカブ",ra:346.1902,dec:15.2053,mag:2.49},Scheat:{id:"Scheat",name:"シェアト",ra:345.9436,dec:28.0828,mag:2.42},Algenib:{id:"Algenib",name:"アルゲニブ",ra:3.3089,dec:15.1836,mag:2.83},
 Mirfak:{id:"Mirfak",name:"ミルファク",ra:51.0807,dec:49.8612,mag:1.79},Algol:{id:"Algol",name:"アルゴル",ra:47.0422,dec:40.9556,mag:2.12},
 Sadr:{id:"Sadr",name:"サドル",ra:305.5571,dec:40.2567,mag:2.23},GienahCyg:{id:"GienahCyg",name:"ギェナー",ra:311.5528,dec:33.9703,mag:2.48},Fawaris:{id:"Fawaris",name:"ファワリス",ra:296.2436,dec:45.1308,mag:2.87},
 Kochab:{id:"Kochab",name:"コカブ",ra:222.6764,dec:74.1555,mag:2.08},Pherkad:{id:"Pherkad",name:"フェルカド",ra:230.1822,dec:71.8340,mag:3.05},Caph:{id:"Caph",name:"カフ",ra:2.2945,dec:59.1498,mag:2.28},Schedar:{id:"Schedar",name:"シェダル",ra:10.1268,dec:56.5373,mag:2.24},GammaCas:{id:"GammaCas",name:"カシオペヤ座γ",ra:14.1771,dec:60.7167,mag:2.47},Ruchbah:{id:"Ruchbah",name:"ルクバー",ra:21.4539,dec:60.2353,mag:2.68},Segin:{id:"Segin",name:"セギン",ra:28.5989,dec:63.6701,mag:3.35},
 Hamal:{id:"Hamal",name:"ハマル",ra:31.7934,dec:23.4624,mag:2.0},Sheratan:{id:"Sheratan",name:"シェラタン",ra:28.66,dec:20.808,mag:2.64}
};
const STAR={...EXTRA,...S};
const FALLBACK={
 UMa:[["Dubhe","Merak"],["Merak","Phecda"],["Phecda","Megrez"],["Megrez","Alioth"],["Alioth","Mizar"],["Mizar","Alkaid"]],UMi:[["Polaris","Kochab"],["Kochab","Pherkad"]],Cas:[["Caph","Schedar"],["Schedar","GammaCas"],["GammaCas","Ruchbah"],["Ruchbah","Segin"]],
 Ori:[["Betelgeuse","Bellatrix"],["Betelgeuse","Alnitak"],["Alnitak","Alnilam"],["Alnilam","Mintaka"],["Mintaka","Bellatrix"],["Alnitak","Saiph"],["Saiph","Rigel"],["Rigel","Mintaka"]],Cyg:[["Deneb","Sadr"],["Sadr","Albireo"],["Fawaris","Sadr"],["Sadr","GienahCyg"]],Lyr:[["Vega","EpsLyr"]],Gem:[["Castor","Pollux"]],Leo:[["Regulus","Algieba"],["Algieba","Zosma"],["Zosma","Denebola"]],Sco:[["Antares","Dschubba"],["Dschubba","Acrab"],["Antares","Shaula"],["Shaula","Sargas"]],Sgr:[["KausAust","Nunki"],["Nunki","Ascella"],["Ascella","KausAust"]],And:[["Alpheratz","Mirach"],["Mirach","Almach"]],Peg:[["Alpheratz","Scheat"],["Scheat","Markab"],["Markab","Algenib"],["Algenib","Alpheratz"]],Ari:[["Hamal","Sheratan"]],Per:[["Mirfak","Algol"]]
};
const ASTERISM_FALLBACK=[
 {id:"bigdipper",name:"北斗七星",stars:["Dubhe","Merak","Phecda","Megrez","Alioth","Mizar","Alkaid"],lines:FALLBACK.UMa},
 {id:"springarc",name:"春の大曲線",stars:["Alkaid","Arcturus","Spica"],lines:[["Alkaid","Arcturus"],["Arcturus","Spica"]]},
 {id:"springtriangle",name:"春の大三角",stars:["Arcturus","Spica","Denebola"],lines:[["Arcturus","Spica"],["Spica","Denebola"],["Denebola","Arcturus"]]},
 {id:"summertriangle",name:"夏の大三角",stars:["Vega","Deneb","Altair"],lines:[["Vega","Deneb"],["Deneb","Altair"],["Altair","Vega"]]},
 {id:"greatsquare",name:"秋の四辺形",stars:["Alpheratz","Scheat","Markab","Algenib"],lines:[["Alpheratz","Scheat"],["Scheat","Markab"],["Markab","Algenib"],["Algenib","Alpheratz"]]},
 {id:"orionbelt",name:"オリオンの三つ星",stars:["Mintaka","Alnilam","Alnitak"],lines:[["Mintaka","Alnilam"],["Alnilam","Alnitak"]]},
 {id:"wintertriangle",name:"冬の大三角",stars:["Betelgeuse","Sirius","Procyon"],lines:[["Betelgeuse","Sirius"],["Sirius","Procyon"],["Procyon","Betelgeuse"]]},
 {id:"winterdiamond",name:"冬のダイヤモンド",stars:["Capella","Aldebaran","Rigel","Sirius","Procyon","Pollux"],lines:[["Capella","Aldebaran"],["Aldebaran","Rigel"],["Rigel","Sirius"],["Sirius","Procyon"],["Procyon","Pollux"],["Pollux","Capella"]]}
];
const ASTERISMS=(Array.isArray(D.asterisms)&&D.asterisms.length)?D.asterisms:ASTERISM_FALLBACK;
const PLANETS={Mercury:{a:.38710,e:.20563,i:7.005,L:252.251,lp:77.456,node:48.331,per:87.969},Venus:{a:.72333,e:.00677,i:3.395,L:181.980,lp:131.564,node:76.680,per:224.701},Mars:{a:1.52368,e:.09340,i:1.850,L:355.433,lp:336.041,node:49.579,per:686.980},Jupiter:{a:5.20260,e:.04849,i:1.303,L:34.351,lp:14.331,node:100.464,per:4332.589},Saturn:{a:9.55491,e:.05551,i:2.489,L:50.077,lp:93.057,node:113.665,per:10759.22},Uranus:{a:19.21845,e:.04630,i:.773,L:314.055,lp:173.005,node:74.006,per:30685.4},Neptune:{a:30.11039,e:.00899,i:1.770,L:304.348,lp:48.124,node:131.784,per:60189}}, EARTH={a:1,e:.01671,L:100.464,lp:102.937,per:365.256};
const PLANET_NAMES={Mercury:"水星",Venus:"金星",Mars:"火星",Jupiter:"木星",Saturn:"土星",Uranus:"天王星",Neptune:"海王星"};
const PLANET_COLORS={Mercury:"#aaa7a0",Venus:"#f2dfb1",Mars:"#d36f43",Jupiter:"#d7bea0",Saturn:"#e2cf94",Uranus:"#a8d7da",Neptune:"#6f88d5"};
const PLANET_LABEL_COLORS={Mercury:"#cfcbc3",Venus:"#fff0c9",Mars:"#ef9a72",Jupiter:"#ead2b6",Saturn:"#f1dda5",Uranus:"#c7eff0",Neptune:"#a8b9f0"};
const DIR16=["北","北北東","北東","東北東","東","東南東","南東","南南東","南","南南西","南西","西南西","西","西北西","北西","北北西"];
const dir16=az=>DIR16[Math.round(norm(az)/22.5)%16];
const STANDARD_LINES=Object.fromEntries((D.constellationStandard||[]).map(c=>[c.abbr||c.id,(c.lines||[]).map(x=>[x[0],x[1]])]));
const DB_LINE_STARS=Object.fromEntries((D.constellationLineStars||[]).filter(x=>x.ra!=null&&x.dec!=null&&Number.isFinite(Number(x.ra))&&Number.isFinite(Number(x.dec))).map(x=>[x.id,{id:x.id,hip:x.hip,ra:Number(x.ra),dec:Number(x.dec),mag:Number.isFinite(Number(x.mag))?Number(x.mag):6,name:x.name||null}]));
let WSTARS={...DB_LINE_STARS},WLINES={...STANDARD_LINES},FULL_LINES=Object.keys(STANDARD_LINES).length===88,ONLINE_STARS=[],ONLINE_STAR_BY_ID={},USER_STARS={},MW_DATA=null,NIGHT_COMETS=[],METEORS=[];
const LINE_CACHE="astrorium_western_lines_v3", STAR_CACHE_LEGACY="astrorium_d3_stars6_v1", MW_CACHE="astrorium_mw_v1", COMET_CACHE="astrorium_comets_v1", METEOR_CACHE="astrorium_meteors_v1";
const STAR_IDB_NAME="nicole-astrorium-star-catalog", STAR_IDB_STORE="catalog", STAR_IDB_KEY="d3-celestial-stars8-v1";
const LINE_URLS=["https://raw.githubusercontent.com/creativival/hipparcos_planetarium_data_creator/main/data/hip_constellation_line.csv","https://creativival.github.io/hipparcos_planetarium_data_creator/data/hip_constellation_line.csv"];
const STARLINE_URLS=["https://raw.githubusercontent.com/creativival/hipparcos_planetarium_data_creator/main/data/hip_constellation_line_star.csv","https://creativival.github.io/hipparcos_planetarium_data_creator/data/hip_constellation_line_star.csv"];
const ONLINE_STAR_URL="https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/stars.8.json";
const ONLINE_STAR_FALLBACK_URL="https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/stars.6.json";
const MW_URLS=["https://raw.githubusercontent.com/sergio-dr/mw_geojson/main/mw_simplified_43p.json","https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/mw.json"];
const COMET_URL="https://astro-nicole.hideld12.workers.dev/night-comets";
const METEOR_URL="https://astro-nicole.hideld12.workers.dev/meteors";
function cacheGet(k){try{return JSON.parse(localStorage.getItem(k)||"null")}catch(e){return null}}function cacheSet(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function starCatalogDb(){return new Promise((resolve,reject)=>{if(!("indexedDB" in window))return reject(new Error("IndexedDB unavailable"));const q=indexedDB.open(STAR_IDB_NAME,1);q.onupgradeneeded=()=>{const db=q.result;if(!db.objectStoreNames.contains(STAR_IDB_STORE))db.createObjectStore(STAR_IDB_STORE)};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error||new Error("IndexedDB open failed"))})}
async function starCatalogGet(){let db;try{db=await starCatalogDb();return await new Promise((resolve,reject)=>{const tx=db.transaction(STAR_IDB_STORE,"readonly"),q=tx.objectStore(STAR_IDB_STORE).get(STAR_IDB_KEY);q.onsuccess=()=>resolve(q.result||null);q.onerror=()=>reject(q.error)})}catch(_){return null}finally{try{db?.close()}catch(_){}}}
async function starCatalogSet(value){let db;try{db=await starCatalogDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STAR_IDB_STORE,"readwrite");tx.objectStore(STAR_IDB_STORE).put(value,STAR_IDB_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error("IndexedDB transaction aborted"))});return true}catch(_){return false}finally{try{db?.close()}catch(_){}}}
function parseD3Stars(d){return(d?.features||[]).map(f=>{const lon=Number(f.geometry?.coordinates?.[0]),dec=Number(f.geometry?.coordinates?.[1]),mag=Number(f.properties?.mag),bv=Number(f.properties?.bv);return{id:"HIP"+f.id,hip:f.id,ra:lon<0?lon+360:lon,dec,mag,bv:Number.isFinite(bv)?bv:null}}).filter(x=>Number.isFinite(x.ra)&&Number.isFinite(x.dec)&&Number.isFinite(x.mag))}
function installOnlineStars(arr){ONLINE_STARS=Array.isArray(arr)?arr:[];ONLINE_STAR_BY_ID=Object.fromEntries(ONLINE_STARS.map(x=>[x.id,x]));enrichNamedStarColors()}
function jd(d){return d.getTime()/864e5+2440587.5}function gmst(j){const T=(j-2451545)/36525;return norm(280.46061837+360.98564736629*(j-2451545)+.000387933*T*T-T*T*T/38710000)}
let FRAME_ASTRO=null;function setFrameAstro(date,lat,lon){const tm=date.getTime(),la=Number(lat)*R,lst=norm(gmst(jd(date))+Number(lon)),lr=lst*R;FRAME_ASTRO={tm,lat:Number(lat),lon:Number(lon),lst,sinLst:Math.sin(lr),cosLst:Math.cos(lr),sinLat:Math.sin(la),cosLat:Math.cos(la)}}function altaz(ra,dec,date,lat,lon){const tm=date.getTime(),fc=FRAME_ASTRO&&FRAME_ASTRO.tm===tm&&FRAME_ASTRO.lat===Number(lat)&&FRAME_ASTRO.lon===Number(lon)?FRAME_ASTRO:null;let H=norm((fc?fc.lst:gmst(jd(date))+Number(lon))-ra);if(H>180)H-=360;const h=H*R,de=dec*R,sd=Math.sin(de),cd=Math.cos(de),sinLat=fc?fc.sinLat:Math.sin(Number(lat)*R),cosLat=fc?fc.cosLat:Math.cos(Number(lat)*R),ch=Math.cos(h),alt=Math.asin(clamp(sd*sinLat+cd*cosLat*ch,-1,1)),y=-Math.sin(h)*cd,x=sd*cosLat-cd*sinLat*ch;return{alt:alt/R,az:norm(Math.atan2(y,x)/R)}}
function refractionDeg(alt){if(alt<-1||alt>89.9)return 0;return (1.02/Math.tan((alt+10.3/(alt+5.11))*R))/60}function apparentAlt(alt){return alt+refractionDeg(alt)}
function sun(j){const T=(j-2451545)/36525,L=norm(280.46646+36000.76983*T+.0003032*T*T),M=norm(357.52911+35999.05029*T-.0001537*T*T),cc=(1.914602-.004817*T-.000014*T*T)*Math.sin(M*R)+(.019993-.000101*T)*Math.sin(2*M*R)+.000289*Math.sin(3*M*R),om=125.04-1934.136*T,lam=L+cc-.00569-.00478*Math.sin(om*R),eps=(23+26/60+21.448/3600-(46.815*T+.00059*T*T-.001813*T*T*T)/3600+.00256*Math.cos(om*R))*R,er=hel(EARTH,j).r||1;return{ra:norm(Math.atan2(Math.cos(eps)*Math.sin(lam*R),Math.cos(lam*R))/R),dec:Math.asin(Math.sin(eps)*Math.sin(lam*R))/R,distanceAU:er,distanceKm:er*AU_KM}}
function moon(j){const T=(j-2451545)/36525,L=norm(218.3164477+481267.88123421*T),Dd=norm(297.8501921+445267.1114034*T),M=norm(357.5291092+35999.0502909*T),Mp=norm(134.9633964+477198.8675055*T),F=norm(93.272095+483202.0175233*T),dr=Dd*R,mr=M*R,mpr=Mp*R,fr=F*R,dL=6.288774*Math.sin(mpr)+1.274027*Math.sin(2*dr-mpr)+.658314*Math.sin(2*dr)+.213618*Math.sin(2*mpr)-.185116*Math.sin(mr)-.114332*Math.sin(2*fr),dB=5.128122*Math.sin(fr)+.280602*Math.sin(mpr+fr)+.277693*Math.sin(mpr-fr)+.173237*Math.sin(2*dr-fr),lam=L+dL,b=dB,eps=(23+26/60+21.448/3600-46.815*T/3600)*R,distanceKm=385000.56-20905.355*Math.cos(mpr)-3699.111*Math.cos(2*dr-mpr)-2955.968*Math.cos(2*dr)-569.925*Math.cos(2*mpr);return{ra:norm(Math.atan2(Math.sin(lam*R)*Math.cos(eps)-Math.tan(b*R)*Math.sin(eps),Math.cos(lam*R))/R),dec:Math.asin(Math.sin(b*R)*Math.cos(eps)+Math.cos(b*R)*Math.sin(eps)*Math.sin(lam*R))/R,distanceKm}}
function kep(M,e){M*=R;let E=M;for(let i=0;i<8;i++)E-=(E-e*Math.sin(E)-M)/(1-e*Math.cos(E));return E}function hel(el,j){const d=j-2451545,n=360/el.per,M=norm(el.L-el.lp+n*d),E=kep(M,el.e),x=el.a*(Math.cos(E)-el.e),y=el.a*Math.sqrt(1-el.e*el.e)*Math.sin(E),v=Math.atan2(y,x),rr=Math.hypot(x,y),lp=el.lp*R,no=(el.node||0)*R,ii=(el.i||0)*R,lo=v+lp;return{x:rr*(Math.cos(no)*Math.cos(lo-no)-Math.sin(no)*Math.sin(lo-no)*Math.cos(ii)),y:rr*(Math.sin(no)*Math.cos(lo-no)+Math.cos(no)*Math.sin(lo-no)*Math.cos(ii)),z:rr*Math.sin(lo-no)*Math.sin(ii),r:rr}}
function planet(name,j){const p=hel(PLANETS[name],j),e=hel(EARTH,j),x=p.x-e.x,y=p.y-e.y,z=p.z-e.z,distAU=Math.hypot(x,y,z),eps=23.4393*R,yy=y*Math.cos(eps)-z*Math.sin(eps),zz=y*Math.sin(eps)+z*Math.cos(eps);return{ra:norm(Math.atan2(yy,x)/R),dec:Math.atan2(zz,Math.hypot(x,yy))/R,distanceAU:distAU,distanceKm:distAU*AU_KM}}
function sunsetForDate(date,lat,lon){const d=new Date(date);d.setHours(0,0,0,0);const target=-.833;let prevT=d.getTime(),prev=altaz(sun(jd(new Date(prevT))).ra,sun(jd(new Date(prevT))).dec,new Date(prevT),lat,lon).alt;for(let m=10;m<=36*60;m+=10){const t=d.getTime()+m*60000,dt=new Date(t),su=sun(jd(dt)),a=altaz(su.ra,su.dec,dt,lat,lon).alt;if(prev>target&&a<=target){let lo=prevT,hi=t;for(let i=0;i<16;i++){const mid=(lo+hi)/2,md=new Date(mid),ms=sun(jd(md)),ma=altaz(ms.ra,ms.dec,md,lat,lon).alt;if(ma>target)lo=mid;else hi=mid}const res=new Date((lo+hi)/2);if(res.getDate()===d.getDate()||res.getTime()-d.getTime()<30*3600000)return res}prev=a;prevT=t}return null}
function makeState(){return{location:{name:"帯広",lat:42.9236,lon:143.1965,alt:0},time:new Date(),running:false,rate:60,projection:"perspective",camera:{az:180,alt:50,fov:120},global:{stars:true,starNames:false,planets:true,planetNames:false,sun:true,sunName:false,ecliptic:false,daylight:true,moon:true,moonName:false,lunarPath:false,moonlight:true,lines:false,names:false,arts:false,asterisms:false,milkyWay:true,dso:false,dsoNames:false,naturalDeepSky:true,smallBodies:false,cometNames:false,radecGrid:false,altazGrid:false,meteors:false,meteorNames:false,sporadicMeteors:false,sporadicMeteorAmount:2,showerMeteors:false,showerMeteorAmount:2,time:false,direction:false,coordinates:false,scintillation:true,scintillationStrength:1,aurora:false,auroraIntensity:1,magMode:"auto",mag:6},constellations:{},asterisms:{},highlights:{},labels:{},annotations:[],draftAnnotation:null,meteorEvents:[],selected:null,customConstellationLines:{},customConstellationStars:{},constellationStarExclusions:{},customConstellations:[],artOverrides:{},media:{active:false,id:null,type:null,name:"",fit:"contain",loop:true,muted:true},display:{starScale:5,starBrightness:1,objectTextScale:4,constellationTextScale:4,hudTextScale:4,milkyWayBrightness:1}}}
function registerUserStars(items){const arr=Array.isArray(items)?items:Object.values(items||{});for(const st of arr){if(!st||!st.id)continue;const ra=Number(st.ra),dec=Number(st.dec),mag=st.mag==null?NaN:Number(st.mag);if(!Number.isFinite(ra)||!Number.isFinite(dec))continue;USER_STARS[String(st.id)]={...st,id:String(st.id),ra:norm(ra),dec:clamp(dec,-90,90),mag:Number.isFinite(mag)?mag:6}}return Object.values(USER_STARS)}function registerConstellationStarMap(map){for(const list of Object.values(map||{}))registerUserStars(list);return USER_STARS}function userStars(){return Object.values(USER_STARS)}function lineStars(){return Object.values(WSTARS)}
function revive(x){x=typeof x==="string"?JSON.parse(x):x;x.time=new Date(x.time);x.location=x.location||{};x.global={...makeState().global,...(x.global||{})};x.camera={...makeState().camera,...(x.camera||{})};x.display={...makeState().display,...(x.display||{})};x.constellations=x.constellations||{};x.asterisms=x.asterisms||{};x.highlights=x.highlights||{};x.labels=x.labels||{};x.annotations=x.annotations||[];x.meteorEvents=x.meteorEvents||[];x.customConstellationLines=x.customConstellationLines||{};x.customConstellationStars=x.customConstellationStars||{};x.constellationStarExclusions=x.constellationStarExclusions||{};x.customConstellations=Array.isArray(x.customConstellations)?x.customConstellations:[];registerConstellationStarMap(x.customConstellationStars);for(const c of x.customConstellations)registerUserStars(c&&c.stars);x.artOverrides=x.artOverrides||{};x.media={...makeState().media,...(x.media||{})};return x}function serial(s){return JSON.stringify({...s,time:s.time.toISOString()})}
function ensureC(s,id){return s.constellations[id]||(s.constellations[id]={line:null,art:null,name:null})}function effectiveConst(s,id,key){const c=ensureC(s,id),v=c[key];if(key==="line"||key==="name"||key==="art"){const g=key==="line"?"lines":key==="name"?"names":"arts";return v==null?!!s.global[g]:!!v}return!!v}function effectiveAst(s,id){return s.asterisms[id]===undefined?!!s.global.asterisms:!!s.asterisms[id]}
function command(s,c){switch(c.type){case"global":s.global[c.key]=!!c.value;break;case"const":ensureC(s,c.id)[c.key]=c.value;break;case"asterism":s.asterisms[c.id]=!!c.value;break;case"highlight":s.highlights[c.id]=!!c.value;break;case"label":s.labels[c.id]=!!c.value;break;case"time":s.time=new Date(c.value);break;case"step":s.time=new Date(s.time.getTime()+Number(c.ms||0));break;case"run":s.running=!!c.value;break;case"rate":s.rate=Number(c.value)||1;break;case"projection":s.projection=c.value==="allsky"?"allsky":"perspective";break;case"camera":s.camera={...s.camera,...c.value};s.camera.az=norm(Number(s.camera.az)||0);s.camera.alt=clamp(Number(s.camera.alt)||0,-20,90);s.camera.fov=clamp(Number(s.camera.fov)||120,20,150);break;case"location":s.location={...s.location,...c.value};break;case"select":s.selected=c.id;break;case"annotations":s.annotations=c.value||[];break;case"draft":s.draftAnnotation=c.value||null;break}return s}
function projectRaw(az,alt,s,w,h){if(s.projection==="allsky"){const rad=Math.min(w,h)*.47,rr=(90-alt)/90*rad,a=az*R;return{x:w/2-rr*Math.sin(a),y:h/2-rr*Math.cos(a),z:1}}let da=norm(az-s.camera.az);if(da>180)da-=360;da*=R;const a=alt*R,ca=s.camera.alt*R,x=Math.cos(a)*Math.sin(da),y=Math.sin(a)*Math.cos(ca)-Math.cos(a)*Math.cos(da)*Math.sin(ca),z=Math.sin(a)*Math.sin(ca)+Math.cos(a)*Math.cos(da)*Math.cos(ca);if(z<=.015)return null;const f=(w/2)/Math.tan(s.camera.fov*R/2);return{x:w/2+f*x/z,y:h/2-f*y/z,z}}
function screenToAltAz(px,py,s,w,h){if(s.projection==="allsky"){const rad=Math.min(w,h)*.47,dx=px-w/2,dy=py-h/2,rr=Math.hypot(dx,dy);if(rr>rad*1.05)return null;const alt=90-(rr/rad)*90,az=norm(Math.atan2(-dx,-dy)/R);return{az,alt}}const f=(w/2)/Math.tan(s.camera.fov*R/2),u=(px-w/2)/f,v=-(py-h/2)/f,nn=Math.hypot(u,v,1),x=u/nn,y=v/nn,z=1/nn,ca=s.camera.alt*R,sinAlt=clamp(y*Math.cos(ca)+z*Math.sin(ca),-1,1),alt=Math.asin(sinAlt),horiz=-y*Math.sin(ca)+z*Math.cos(ca),da=Math.atan2(x,horiz);return{az:norm(s.camera.az+da/R),alt:alt/R}}
function altAzToRaDec(az,alt,date,lat,lon){const A=az*R,h=alt*R,ph=lat*R,sinDec=clamp(Math.sin(h)*Math.sin(ph)+Math.cos(h)*Math.cos(ph)*Math.cos(A),-1,1),dec=Math.asin(sinDec),cd=Math.max(1e-9,Math.cos(dec)),sinH=-Math.sin(A)*Math.cos(h)/cd,cosH=(Math.sin(h)*Math.cos(ph)-Math.cos(h)*Math.sin(ph)*Math.cos(A))/cd,H=Math.atan2(sinH,cosH)/R,lst=norm(gmst(jd(date))+lon),ra=norm(lst-H);return{ra,dec:dec/R}}
function screenToRaDec(px,py,s,w,h){const a=screenToAltAz(px,py,s,w,h);return a?altAzToRaDec(a.az,a.alt,s.time,s.location.lat,s.location.lon):null}
function findAltCrossing(body,date,lat,lon,target,rising){const base=new Date(date);base.setHours(0,0,0,0);let prevT=base.getTime(),prev=(()=>{const o=body(jd(new Date(prevT)));return altaz(o.ra,o.dec,new Date(prevT),lat,lon).alt})();for(let m=1;m<=1440;m++){const t=base.getTime()+m*60000,d=new Date(t),o=body(jd(d)),cur=altaz(o.ra,o.dec,d,lat,lon).alt;if((rising&&prev<=target&&cur>target)||(!rising&&prev>=target&&cur<target)){const frac=rising?(target-prev)/(cur-prev):(prev-target)/(prev-cur);return new Date(base.getTime()+((m-1)+frac)*60000)}prev=cur;prevT=t}return null}
function moonPhaseInfo(date){const syn=29.530588853,epoch=2451550.1,age=((jd(date)-epoch)%syn+syn)%syn,illum=(1-Math.cos(2*Math.PI*age/syn))/2;let icon;if(age<1.85||age>=27.68)icon="🌑";else if(age<5.54)icon="🌒";else if(age<9.23)icon="🌓";else if(age<12.92)icon="🌔";else if(age<16.61)icon="🌕";else if(age<20.30)icon="🌖";else if(age<23.99)icon="🌗";else icon="🌘";return{moonAge:Math.round(age*10)/10,moonIllum:Math.round(illum*100),moonPhase:icon}}
function calcSkyInfo(lat,lon,date){const sunrise=findAltCrossing(sun,date,lat,lon,-.833,true),sunset=findAltCrossing(sun,date,lat,lon,-.833,false),astroMorning=findAltCrossing(sun,date,lat,lon,-18,true),astroEvening=findAltCrossing(sun,date,lat,lon,-18,false),moonRise=findAltCrossing(moon,date,lat,lon,-.833,true),moonSet=findAltCrossing(moon,date,lat,lon,-.833,false),ph=moonPhaseInfo(date);return{sunrise,sunset,astroMorning,astroEvening,moonRise,moonSet,...ph}}

function point(o,s,w,h){if(!o||!Number.isFinite(Number(o.ra))||!Number.isFinite(Number(o.dec)))return null;const a=altaz(Number(o.ra),Number(o.dec),s.time,s.location.lat,s.location.lon),aa=apparentAlt(a.alt);if(s.projection==="allsky"&&aa<0)return null;return projectRaw(a.az,aa,s,w,h)}
const ART_IMAGE_OVERRIDE_SRC={};function artImage(id){const def=ART[id];if(!def)return null;const src=ART_IMAGE_OVERRIDE_SRC[id]||def.src;let im=ART_IMAGES[id];if(!im||im.__nicoleSrc!==src){im=new Image();im.decoding="async";im.__nicoleSrc=src;im.src=src;ART_IMAGES[id]=im}return im}function setArtImageOverride(id,src){if(!ART[id])return false;if(src)ART_IMAGE_OVERRIDE_SRC[id]=String(src);else delete ART_IMAGE_OVERRIDE_SRC[id];delete ART_IMAGES[id];invalidateArtMesh(id);return true}
function artSkyPoint(def,u,v){const ra0=Number(def.ra)*R,de0=Number(def.dec)*R,cr=Math.cos(ra0),sr=Math.sin(ra0),cd=Math.cos(de0),sd=Math.sin(de0),cx=cd*cr,cy=cd*sr,cz=sd,ex=-sr,ey=cr,ez=0,nx=-sd*cr,ny=-sd*sr,nz=cd,flip=def.flipX?-1:1,flipy=def.flipY?-1:1,wid=(Number(def.widthDeg)||25)*R,hei=(Number(def.heightDeg)||25)*R,th=(Number(def.rotationDeg)||0)*R,ct=Math.cos(th),st=Math.sin(th),x=(u-.5)*wid*flip,yn=(.5-v)*hei*flipy,east=x*ct-yn*st,north=x*st+yn*ct,tx=Math.tan(east),ty=Math.tan(north),qx=cx+tx*ex+ty*nx,qy=cy+tx*ey+ty*ny,qz=cz+tx*ez+ty*nz,ll=Math.hypot(qx,qy,qz)||1;return{ra:norm(Math.atan2(qy/ll,qx/ll)/R),dec:Math.asin(clamp(qz/ll,-1,1))/R}}
function artProject(o,s,w,h){const a=altaz(o.ra,o.dec,s.time,s.location.lat,s.location.lon),aa=apparentAlt(a.alt);if(s.projection==="allsky"){if(aa<0)return null;return projectRaw(a.az,aa,s,w,h)}const p=projectRaw(a.az,aa,s,w,h);if(!p||p.z<.025)return null;return p}
function drawImageTriangle(ctx,im,src,dst,crop){const [s0,s1,s2]=src,[d0,d1,d2]=dst,den=s0.x*(s1.y-s2.y)+s1.x*(s2.y-s0.y)+s2.x*(s0.y-s1.y);if(Math.abs(den)<1e-6)return;const a=(d0.x*(s1.y-s2.y)+d1.x*(s2.y-s0.y)+d2.x*(s0.y-s1.y))/den,c=(d0.x*(s2.x-s1.x)+d1.x*(s0.x-s2.x)+d2.x*(s1.x-s0.x))/den,e=(d0.x*(s1.x*s2.y-s2.x*s1.y)+d1.x*(s2.x*s0.y-s0.x*s2.y)+d2.x*(s0.x*s1.y-s1.x*s0.y))/den,b=(d0.y*(s1.y-s2.y)+d1.y*(s2.y-s0.y)+d2.y*(s0.y-s1.y))/den,d=(d0.y*(s2.x-s1.x)+d1.y*(s0.x-s2.x)+d2.y*(s1.x-s0.x))/den,f=(d0.y*(s1.x*s2.y-s2.x*s1.y)+d1.y*(s2.x*s0.y-s0.x*s2.y)+d2.y*(s0.x*s1.y-s1.x*s0.y))/den;ctx.save();ctx.beginPath();ctx.moveTo(d0.x,d0.y);ctx.lineTo(d1.x,d1.y);ctx.lineTo(d2.x,d2.y);ctx.closePath();ctx.clip();ctx.setTransform(a,b,c,d,e,f);ctx.drawImage(im,crop.x,crop.y,crop.w,crop.h,crop.x,crop.y,crop.w,crop.h);ctx.restore()}
function artMesh(id,def,nx,ny){const key=id+":"+nx+"x"+ny;if(ART_MESH_CACHE[key])return ART_MESH_CACHE[key];const sky=Array.from({length:ny+1},()=>Array(nx+1));for(let j=0;j<=ny;j++)for(let i=0;i<=nx;i++)sky[j][i]=artSkyPoint(def,i/nx,j/ny);return ART_MESH_CACHE[key]=sky}function invalidateArtMesh(id){for(const k of Object.keys(ART_MESH_CACHE))if(!id||k.startsWith(id+":"))delete ART_MESH_CACHE[k];ART_CONFIG_REV++}function applyArtConfig(id,patch){if(!ART[id]||!patch)return false;Object.assign(ART[id],patch);invalidateArtMesh(id);return true}
const ART_BASE_STATE=JSON.parse(JSON.stringify(ART));let ART_OVERRIDE_STATE_KEY="";function applyArtOverrides(overrides){overrides=overrides&&typeof overrides==="object"?overrides:{};let key="";try{key=JSON.stringify(overrides)}catch(e){}if(key===ART_OVERRIDE_STATE_KEY)return false;const ids=new Set([...Object.keys(ART_BASE_STATE),...Object.keys(overrides)]);for(const id of ids){if(!ART[id]||!ART_BASE_STATE[id])continue;Object.assign(ART[id],JSON.parse(JSON.stringify(ART_BASE_STATE[id])));if(overrides[id]&&typeof overrides[id]==="object")Object.assign(ART[id],overrides[id]);invalidateArtMesh(id)}ART_OVERRIDE_STATE_KEY=key;return true}
function artMeshDensity(def,s,w,h,bias=0){const c=artProject({ra:Number(def.ra),dec:Number(def.dec)},s,w,h);let edge=1.2;if(c)edge=Math.max(Math.abs(c.x-w/2)/(w/2),Math.abs(c.y-h/2)/(h/2));let base;if(s.projection==="allsky")base=5;else if(edge<.62&&s.camera.fov<=105)base=3;else if(edge<1.05&&s.camera.fov<=125)base=4;else if(edge<1.35)base=5;else base=6;const maxDim=Math.max(Number(def.widthDeg)||25,Number(def.heightDeg)||25),sx=Math.max(.58,(Number(def.widthDeg)||25)/maxDim),sy=Math.max(.58,(Number(def.heightDeg)||25)/maxDim);base=Math.max(2,base+Number(bias||0));const minMesh=bias<0?2:3;return{nx:clamp(Math.round(base*sx),minMesh,6),ny:clamp(Math.round(base*sy),minMesh,6)}}
function artMayBeVisible(def,s,w,h){const a=altaz(Number(def.ra),Number(def.dec),s.time,s.location.lat,s.location.lon),radius=.55*Math.hypot(Number(def.widthDeg)||25,Number(def.heightDeg)||25);if(s.projection==="allsky")return apparentAlt(a.alt)+radius>-4;const ca=s.camera.alt*R,aa=apparentAlt(a.alt)*R,da=(norm(a.az-s.camera.az+180)-180)*R,sep=Math.acos(clamp(Math.sin(ca)*Math.sin(aa)+Math.cos(ca)*Math.cos(aa)*Math.cos(da),-1,1))/R,f=s.camera.fov*R/2,diag=Math.atan(Math.sqrt(1+(h/w)*(h/w))*Math.tan(f))/R;return sep<diag+radius+7}
function drawConstellationArt(ctx,s,w,h,id,alpha,meshBias=0){const def=ART[id];if(!def||alpha<=0||!artMayBeVisible(def,s,w,h))return;const im=artImage(id);if(!im||!im.complete||!im.naturalWidth)return;const {nx,ny}=artMeshDensity(def,s,w,h,meshBias),sky=artMesh(id,def,nx,ny),pts=Array.from({length:ny+1},()=>Array(nx+1));let visible=0;for(let j=0;j<=ny;j++)for(let i=0;i<=nx;i++){const p=artProject(sky[j][i],s,w,h);pts[j][i]=p;if(p&&p.x>-w*.35&&p.x<w*1.35&&p.y>-h*.35&&p.y<h*1.35)visible++}if(!visible)return;ctx.save();ctx.globalAlpha=clamp(alpha*(Number(def.opacity)||.58),0,1);ctx.globalCompositeOperation="screen";ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="medium";const sw=im.naturalWidth/nx,sh=im.naturalHeight/ny,maxEdge=Math.max(w,h)*1.9;for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const p00=pts[j][i],p10=pts[j][i+1],p01=pts[j+1][i],p11=pts[j+1][i+1];if(!p00||!p10||!p01||!p11)continue;const minx=Math.min(p00.x,p10.x,p01.x,p11.x),maxx=Math.max(p00.x,p10.x,p01.x,p11.x),miny=Math.min(p00.y,p10.y,p01.y,p11.y),maxy=Math.max(p00.y,p10.y,p01.y,p11.y);if(maxx<0||minx>w||maxy<0||miny>h)continue;const e1=Math.hypot(p00.x-p10.x,p00.y-p10.y),e2=Math.hypot(p10.x-p11.x,p10.y-p11.y),e3=Math.hypot(p11.x-p01.x,p11.y-p01.y),e4=Math.hypot(p01.x-p00.x,p01.y-p00.y),ed=Math.hypot(p00.x-p11.x,p00.y-p11.y);if(Math.max(e1,e2,e3,e4,ed)>maxEdge)continue;const x0=i*sw,y0=j*sh,x1=(i+1)*sw,y1=(j+1)*sh,crop={x:Math.max(0,x0-1),y:Math.max(0,y0-1),w:Math.min(im.naturalWidth,x1+1)-Math.max(0,x0-1),h:Math.min(im.naturalHeight,y1+1)-Math.max(0,y0-1)};drawImageTriangle(ctx,im,[{x:x0,y:y0},{x:x1,y:y0},{x:x0,y:y1}],[p00,p10,p01],crop);drawImageTriangle(ctx,im,[{x:x1,y:y0},{x:x1,y:y1},{x:x0,y:y1}],[p10,p11,p01],crop)}ctx.restore()}
function artLayerMode(count,s,opts){if(opts.preview||count<=10)return{mode:"direct",scale:1,interval:0,bias:0};if(count<=30)return{mode:"layer-medium",scale:.72,interval:1000/30,bias:-1};if(s.projection==="allsky")return{mode:"layer-allsky",scale:.45,interval:1000/12,bias:-2};return{mode:"layer-many",scale:.55,interval:1000/18,bias:-2}}
function ensureArtLayer(w,h,scale){const cw=Math.max(240,Math.round(w*scale)),ch=Math.max(135,Math.round(h*scale));if(!ART_LAYER_CACHE.canvas){ART_LAYER_CACHE.canvas=document.createElement("canvas");ART_LAYER_CACHE.ctx=ART_LAYER_CACHE.canvas.getContext("2d",{alpha:true})}if(ART_LAYER_CACHE.canvas.width!==cw||ART_LAYER_CACHE.canvas.height!==ch){ART_LAYER_CACHE.canvas.width=cw;ART_LAYER_CACHE.canvas.height=ch;ART_LAYER_CACHE.lastStructure=""}return ART_LAYER_CACHE}
function drawConstellationArts(ctx,s,w,h,entries,opts={}){if(!entries.length)return;const cfg=artLayerMode(entries.length,s,opts);if(cfg.mode==="direct"){for(const e of entries)drawConstellationArt(ctx,s,w,h,e.id,e.alpha,0);return}const cache=ensureArtLayer(w,h,cfg.scale),now=performance.now(),ids=entries.map(e=>e.id+":"+Math.round(e.alpha*20)).join(","),structure=[cfg.mode,cache.canvas.width,cache.canvas.height,s.projection,ids,ART_CONFIG_REV].join("|"),motion=[Math.round(s.camera.az*20)/20,Math.round(s.camera.alt*20)/20,Math.round(s.camera.fov*20)/20,Math.round(s.time.getTime()/20),Math.round(s.location.lat*1000),Math.round(s.location.lon*1000)].join("|"),structureChanged=structure!==cache.lastStructure,motionChanged=motion!==cache.lastMotion,need=structureChanged||(motionChanged&&now-cache.lastDraw>=cfg.interval);if(need){const cc=cache.ctx,cw=cache.canvas.width,ch=cache.canvas.height;cc.setTransform(1,0,0,1,0,0);cc.globalAlpha=1;cc.globalCompositeOperation="source-over";cc.clearRect(0,0,cw,ch);for(const e of entries)drawConstellationArt(cc,s,cw,ch,e.id,e.alpha,cfg.bias);cache.lastDraw=now;cache.lastStructure=structure;cache.lastMotion=motion;cache.mode=cfg.mode;cache.scale=cfg.scale;cache.interval=cfg.interval}ctx.save();ctx.globalAlpha=1;ctx.globalCompositeOperation="source-over";ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="medium";ctx.drawImage(cache.canvas,0,0,w,h);ctx.restore()}
function inside(p,w,h,m=0){return p&&p.x>=-m&&p.x<=w+m&&p.y>=-m&&p.y<=h+m}
function coordFor(id){return STAR[id]||WSTARS[id]||USER_STARS[id]||ONLINE_STAR_BY_ID[id]||null}
function baseSegmentsFor(abbr){return STANDARD_LINES[abbr]||WLINES[abbr]||FALLBACK[abbr]||[]}
function segmentsFor(abbr,s){const m=s?.customConstellationLines;if(m&&Object.prototype.hasOwnProperty.call(m,abbr))return m[abbr]||[];return baseSegmentsFor(abbr)}
function constellationSegments(abbr,s){return (segmentsFor(abbr,s)||[]).map(x=>[x[0],x[1]])}
function originalConstellationSegments(abbr){return (baseSegmentsFor(abbr)||[]).map(x=>[x[0],x[1]])}
function customConstellationCenter(c){if(!c)return null;registerUserStars(c.stars||[]);if(c.center&&Number.isFinite(Number(c.center.ra))&&Number.isFinite(Number(c.center.dec)))return{ra:+c.center.ra,dec:+c.center.dec};const ids=[...new Set((Array.isArray(c.segments)?c.segments:[]).flat().map(String))],pts=ids.map(coordFor).filter(Boolean);if(!pts.length)return null;let x=0,y=0,z=0;for(const q of pts){const ra=Number(q.ra)*R,de=Number(q.dec)*R,cd=Math.cos(de);x+=cd*Math.cos(ra);y+=cd*Math.sin(ra);z+=Math.sin(de)}const n=Math.hypot(x,y,z)||1;return{ra:norm(Math.atan2(y/n,x/n)/R),dec:Math.asin(clamp(z/n,-1,1))/R}}
function onlineStars(){return ONLINE_STARS}
function targetById(id){if(C[id])return{...C[id],kind:"constellation"};if(S[id])return S[id];if(O[id])return O[id];if(PINFO[id])return{...PINFO[id],kind:"planet",...planet(id,jd(new Date()))};if(id==="Sun")return{id:"Sun",name:"太陽",display_name:"太陽",kind:"sun",...sun(jd(new Date()))};if(id==="Moon")return{id:"Moon",name:"月",display_name:"月",kind:"moon",...moon(jd(new Date()))};return null}
function targetPosition(id,date){if(PINFO[id])return planet(id,jd(date));if(id==="Sun")return sun(jd(date));if(id==="Moon")return moon(jd(date));return targetById(id)}
function centerOn(s,id){const o=targetPosition(id,s.time);if(!o)return{ok:false};const a=altaz(o.ra,o.dec,s.time,s.location.lat,s.location.lon);s.camera.az=a.az;if(a.alt>=-1)s.camera.alt=clamp(apparentAlt(a.alt),3,85);s.selected=id;return{ok:a.alt>=0,alt:a.alt,az:a.az}}
function visibleConstellations(s,w,h){const out=[];for(const c of D.constellations){let yes=inside(point(c,s,w,h),w,h,30);if(!yes){for(const x of D.stars){if(x.constellation===c.id&&inside(point(x,s,w,h),w,h,10)){yes=true;break}}}if(!yes){for(const x of D.dsos){if(x.constellation===c.id&&inside(point(x,s,w,h),w,h,10)){yes=true;break}}}if(yes)out.push(c)}return out.sort((a,b)=>a.name.localeCompare(b.name,"ja"))}
function visibleAsterisms(s,w,h){return ASTERISMS.filter(a=>a.stars.some(id=>inside(point(coordFor(id),s,w,h),w,h,20)))}
const csv=t=>String(t||"").replace(/\r/g,"").split("\n").map(x=>x.trim()).filter(Boolean).map(x=>x.split(",").map(v=>v.trim().replace(/^"|"$/g,"")));
function parseLineStars(t){const z={};for(const a of csv(t)){if(a.length<8)continue;let [hip,rh,rm,rs,dd,dm,ds,mag]=a.map(Number);if(![hip,rh,rm,rs,dd,dm,ds].every(Number.isFinite))continue;z["HIP"+hip]={id:"HIP"+hip,ra:(rh+rm/60+rs/3600)*15,dec:dd<0?dd-Math.abs(dm)/60-Math.abs(ds)/3600:dd+Math.abs(dm)/60+Math.abs(ds)/3600,mag:Number.isFinite(mag)?mag:6}}return z}function parseLines(t,s){const z={};for(const a of csv(t)){const ab=a[0],u="HIP"+Number(a[1]),v="HIP"+Number(a[2]);if(ab&&s[u]&&s[v])(z[ab]||(z[ab]=[])).push([u,v])}return z}
async function fetchTimed(url,opts={},timeout=7000){if(/^https?:/i.test(String(url)))throw new Error("offline mode: network disabled");const ac=new AbortController(),t=setTimeout(()=>ac.abort(),timeout);try{return await fetch(url,{...opts,signal:ac.signal})}finally{clearTimeout(t)}}
async function fetchFirst(urls,type="text"){let last;for(const u of urls){try{const r=await fetchTimed(u,{cache:"no-store"},7000);if(!r.ok)throw Error("HTTP "+r.status);return type==="json"?await r.json():await r.text()}catch(e){last=e}}throw last||Error("fetch failed")}
function angSep(ra1,dec1,ra2,dec2){const a=ra1*R,b=dec1*R,c=ra2*R,d=dec2*R,q=Math.sin(b)*Math.sin(d)+Math.cos(b)*Math.cos(d)*Math.cos(a-c);return Math.acos(clamp(q,-1,1))/R}
function bvLabel(bv){if(!Number.isFinite(bv))return"—";if(bv<-.1)return"青白";if(bv<.2)return"青白";if(bv<.45)return"白";if(bv<.75)return"黄白";if(bv<1.0)return"黄";if(bv<1.4)return"橙";return"赤橙"}
function enrichNamedStarColors(){if(!ONLINE_STARS.length)return;for(const st of D.stars){if(st.display_color_hex||Number.isFinite(Number(st.bv)))continue;let best=null,bd=1e9;for(const x of ONLINE_STARS){if(!Number.isFinite(x.bv))continue;const d=angSep(st.ra,st.dec,x.ra,x.dec);if(d<bd){bd=d;best=x}}if(best&&bd<.12){st.bv=best.bv;st.colorLabel=bvLabel(best.bv)}}}
async function loadLines(){
 const standardReady=Object.keys(STANDARD_LINES).length===88;
 const c=cacheGet(LINE_CACHE);
 if(standardReady){
   if(c&&c.s){WSTARS={...c.s,...DB_LINE_STARS};WLINES={...STANDARD_LINES};FULL_LINES=true;return{full:true,standard:true,coordinates:Object.keys(WSTARS).length,cached:true}}
   try{const st=await fetchFirst(STARLINE_URLS),ss=parseLineStars(st);WSTARS={...ss,...DB_LINE_STARS};WLINES={...STANDARD_LINES};FULL_LINES=true;cacheSet(LINE_CACHE,{s:ss,l:STANDARD_LINES,standardVersion:"0.3.2"});return{full:true,standard:true,coordinates:Object.keys(WSTARS).length,cached:false}}catch(e){WSTARS={...DB_LINE_STARS};WLINES={...STANDARD_LINES};FULL_LINES=true;return{full:true,standard:true,coordinates:Object.keys(WSTARS).length,partialCoordinates:true,error:String(e)}}
 }
 if(c&&c.s&&c.l){WSTARS=c.s;WLINES=c.l;FULL_LINES=true;return{full:true}}
 try{const [lt,st]=await Promise.all([fetchFirst(LINE_URLS),fetchFirst(STARLINE_URLS)]),ss=parseLineStars(st),ll=parseLines(lt,ss);if(Object.keys(ll).length<70)throw Error("incomplete");WSTARS=ss;WLINES=ll;FULL_LINES=true;cacheSet(LINE_CACHE,{s:ss,l:ll});return{full:true}}catch(e){return{full:false}}
}
async function importStarCatalogText(text){const stars=parseD3Stars(JSON.parse(text));if(stars.length<1000)throw new Error("星カタログとして読み込めません（"+stars.length+"件）");installOnlineStars(stars);await starCatalogSet({version:1,source:"imported file",maxMag:8,storedAt:Date.now(),stars});return{count:stars.length}}
async function loadOnlineStars(){
 const c=await starCatalogGet();
 if(c&&Array.isArray(c.stars)&&c.stars.length>10000){installOnlineStars(c.stars);return{count:ONLINE_STARS.length,cached:true,source:c.source||"stars.8",maxMag:c.maxMag||8,storage:"indexeddb"}}
 try{
  const r=await fetchTimed(ONLINE_STAR_URL,{cache:"default"},20000);if(!r.ok)throw new Error(`HTTP ${r.status}`);const stars=parseD3Stars(await r.json());if(stars.length<10000)throw new Error(`deep star catalog incomplete (${stars.length})`);
  installOnlineStars(stars);await starCatalogSet({version:1,source:"d3-celestial stars.8.json",maxMag:8,storedAt:Date.now(),stars});try{localStorage.removeItem(STAR_CACHE_LEGACY)}catch(_){}
  return{count:stars.length,cached:false,source:"stars.8",maxMag:8,storage:"indexeddb"}
 }catch(e){
  const old=cacheGet(STAR_CACHE_LEGACY);if(old&&Array.isArray(old)&&old.length>1000){installOnlineStars(old);return{count:old.length,cached:true,source:"stars.6 legacy",maxMag:6,storage:"localstorage",warning:String(e)}}
  try{const r=await fetchTimed(ONLINE_STAR_FALLBACK_URL,{cache:"default"},10000);if(!r.ok)throw new Error(`HTTP ${r.status}`);const stars=parseD3Stars(await r.json());installOnlineStars(stars);return{count:stars.length,cached:false,source:"stars.6 fallback",maxMag:6,warning:String(e)}}catch(e2){return{count:0,error:String(e2),warning:String(e)}}
 }
}
function validMW(d){return d&&d.type==="FeatureCollection"&&Array.isArray(d.features)}async function loadMilkyWay(){buildMilkyWayClouds();return{ok:true,cached:true,mode:"immersive-texture"}}
function interpolateRa(a,b,t){let d=((Number(b)-Number(a)+540)%360)-180;return norm(Number(a)+d*t)}function interpolateEphemeris(points,date){if(!Array.isArray(points)||!points.length)return null;const target=date.getTime(),v=points.map(p=>({...p,_t:new Date(p.time).getTime()})).filter(p=>Number.isFinite(p._t)&&Number.isFinite(Number(p.ra))&&Number.isFinite(Number(p.dec))).sort((a,b)=>a._t-b._t);if(!v.length||target<v[0]._t||target>v[v.length-1]._t)return null;let lo=0,hi=v.length-1;while(hi-lo>1){const m=(lo+hi)>>1;if(v[m]._t<=target)lo=m;else hi=m}const a=v[lo],b=v[Math.min(hi,v.length-1)],f=a._t===b._t?0:(target-a._t)/(b._t-a._t);return{ra:interpolateRa(a.ra,b.ra,f),dec:Number(a.dec)+(Number(b.dec)-Number(a.dec))*f}}
async function loadComets(s){NIGHT_COMETS=[];return{count:0,offline:true};const key=`${s.location.lat.toFixed(3)}:${s.location.lon.toFixed(3)}:${s.time.toISOString().slice(0,10)}`,cached=cacheGet(COMET_CACHE);if(cached&&cached.key===key&&Array.isArray(cached.data)){NIGHT_COMETS=cached.data;return{count:NIGHT_COMETS.length,cached:true}}try{const q=new URLSearchParams({lat:String(s.location.lat),lon:String(s.location.lon),alt_m:String(s.location.alt||0),obs_time:s.time.toISOString(),vmag_max:"12",max_comets:"20",step_minutes:"15"});const r=await fetchTimed(COMET_URL+"?"+q,{cache:"no-store"},8000);if(!r.ok)throw Error("HTTP "+r.status);const d=await r.json();NIGHT_COMETS=(d.comets||[]).filter(x=>Array.isArray(x.points));cacheSet(COMET_CACHE,{key,data:NIGHT_COMETS});return{count:NIGHT_COMETS.length}}catch(e){return{count:0,error:String(e)}}}
async function loadMeteors(s){const y=s.time.getFullYear(),T=[["しぶんぎ座流星群","QUA",230,49,"01-01","01-10"],["こと座流星群","LYR",271,34,"04-14","04-30"],["みずがめ座η流星群","ETA",338,-1,"04-19","05-28"],["みずがめ座δ南流星群","SDA",340,-16,"07-12","08-23"],["やぎ座α流星群","CAP",307,-10,"07-03","08-15"],["ペルセウス座流星群","PER",48,58,"07-17","08-24"],["オリオン座流星群","ORI",95,16,"10-02","11-07"],["おうし座南流星群","STA",52,13,"09-10","11-20"],["しし座流星群","LEO",152,22,"11-06","11-30"],["ふたご座流星群","GEM",112,33,"12-04","12-17"],["こぐま座流星群","URS",217,76,"12-17","12-26"]];METEORS=T.map(x=>({name:x[0],code:x[1],ra:x[2],dec:x[3],activeStart:y+"-"+x[4],activeEnd:y+"-"+x[5]}));return{count:METEORS.length,offline:true}}
function mix(a,b,t){return a.map((x,i)=>x+(b[i]-x)*t)}function rgb(c){return`rgb(${c.map(x=>Number(x).toFixed(2)).join(",")})`}function smooth01(x){x=clamp(x,0,1);return x*x*(3-2*x)}function daylightBase(alt){const n=[0,0,1.5],a=[1.5,4,12],na=[7,20,44],ci=[30,72,120],dy=[92,158,205];if(alt<=-18)return n;if(alt<=-12)return mix(n,a,smooth01((alt+18)/6));if(alt<=-6)return mix(a,na,smooth01((alt+12)/6));if(alt<=0)return mix(na,ci,smooth01((alt+6)/6));return mix(ci,dy,smooth01(Math.min(1,alt/12)))}function limitingMag(sunAlt,user){const l0=user,l1=Math.min(user,4.5),l2=Math.min(user,2.2);if(sunAlt<=-18)return l0;if(sunAlt<=-12)return l0+(l1-l0)*smooth01((sunAlt+18)/6);if(sunAlt<=-6)return l1+(l2-l1)*smooth01((sunAlt+12)/6);if(sunAlt<=0)return l2+(-2.2-l2)*smooth01((sunAlt+6)/6);return -2.2+(-5.0+2.2)*smooth01(Math.min(1,sunAlt/12))}function effectiveStarMagLimit(s){const manual=String(s?.global?.magMode||"auto")==="manual";if(manual)return clamp(Number(s?.global?.mag)||6,2,8);if(s?.projection==="allsky")return 6;const f=clamp(Number(s?.camera?.fov)||120,20,150),t=clamp(Math.log2(120/f)/Math.log2(6),0,1);return 6+2*t}
function hexToRgb(h){const m=String(h||"").match(/^#?([0-9a-f]{6})$/i);if(!m)return[255,255,255];const n=parseInt(m[1],16);return[(n>>16)&255,(n>>8)&255,n&255]}
function bvColor(bv){if(!Number.isFinite(bv))return[245,247,255];const t=4600*(1/(.92*bv+1.7)+1/(.92*bv+.62))/100;let r,g,b;if(t<=66){r=255;g=99.4708025861*Math.log(t)-161.1195681661;b=t<=19?0:138.5177312231*Math.log(t-10)-305.0447927307}else{r=329.698727446*Math.pow(t-60,-.1332047592);g=288.1221695283*Math.pow(t-60,-.0755148492);b=255}return[clamp(Math.round(r),0,255),clamp(Math.round(g),0,255),clamp(Math.round(b),0,255)]}
function airmass(alt){if(alt<=0)return 40;const ss=Math.sin(alt*R);return 1/(ss+.50572*Math.pow(alt+6.07995,-1.6364))}
function moonSkyPenalty(s,sunAlt){const mo=moon(jd(s.time)),ma=altaz(mo.ra,mo.dec,s.time,s.location.lat,s.location.lon),night=smooth01(clamp((-sunAlt-2)/10,0,1)),above=smooth01(clamp(ma.alt/8,0,1));if(night<=0||above<=0)return 0;const su=sun(jd(s.time)),sep=Math.acos(clamp(Math.sin(su.dec*R)*Math.sin(mo.dec*R)+Math.cos(su.dec*R)*Math.cos(mo.dec*R)*Math.cos((su.ra-mo.ra)*R),-1,1)),illum=(1-Math.cos(sep))/2;return 2.0*illum*Math.pow(Math.max(0,Math.sin(Math.max(0,ma.alt)*R)),.65)*night*above}
const SCINT={};function scintFactor(id,alt,now,on,strength=1){if(!on||alt<=0||strength<=0)return 1;strength=clamp(Number(strength)||1,0,2);let q=SCINT[id];if(!q){q=SCINT[id]={v:1,target:1,next:now+150+Math.random()*1200,last:now}}const dt=Math.min(100,Math.max(0,now-q.last));q.last=now;if(now>=q.next){const low=1-clamp(Math.sin(Math.max(0,alt)*R),0,1),chance=.12+.70*low;const down=(.04+.34*low)*strength,up=(.02+.10*low)*strength;q.target=Math.random()<chance?1-down*Math.random():1+up*Math.random();q.next=now+90+Math.random()*(1550-950*low)}q.v+=(q.target-q.v)*clamp(dt/120,0,1);return clamp(q.v,Math.max(.18,1-.48*strength),1+.12*strength)}
function starAlpha(mag,alt,sunAlt,id,now,userMax,moonPenalty,scintillation,scintillationStrength=1){const ext=.18*Math.max(0,airmass(alt)-1),m=mag+Math.min(2.4,ext),base=clamp(1.08-(m+1.5)/8.1,.04,1),lim=limitingMag(sunAlt,userMax)-moonPenalty,skyFade=1/(1+Math.exp((m-lim)*3.4)),tw=scintFactor(id,alt,now,scintillation,scintillationStrength);return clamp(base*skyFade*tw,0,1)}
const FADE={};function fade(k,on){const n=performance.now(),f=FADE[k]||(FADE[k]={a:on?0:0,t:n}),dt=Math.min(60,n-f.t);f.t=n;f.a=clamp(f.a+(on?1:-1)*dt/420,0,1);return f.a}
function annPoint(p,s,w,h){if(!p)return null;if(Number.isFinite(p.ra)&&Number.isFinite(p.dec))return point(p,s,w,h);if(Number.isFinite(p.x)&&Number.isFinite(p.y))return{x:p.x*w,y:p.y*h};return null}
function drawAnnotations(ctx,anns,w,h,s){ctx.save();ctx.lineCap="round";ctx.lineJoin="round";ctx.lineWidth=Math.max(2,w/700);for(const a of anns||[]){ctx.strokeStyle=a.color||"#ffd65c";ctx.fillStyle=a.color||"#ffd65c";if(a.type==="pen"&&Array.isArray(a.points)&&a.points.length>1){let prev=null;ctx.beginPath();for(const q of a.points){const p=annPoint(q,s,w,h);if(!p){prev=null;continue}if(!prev||Math.hypot(p.x-prev.x,p.y-prev.y)>w*.25)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);prev=p}ctx.stroke();continue}const p1=a.p1?annPoint(a.p1,s,w,h):annPoint({x:a.x1,y:a.y1},s,w,h),p2=a.p2?annPoint(a.p2,s,w,h):annPoint({x:a.x2,y:a.y2},s,w,h);if(!p1||!p2)continue;ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke();if(a.type==="arrow"){const ang=Math.atan2(p2.y-p1.y,p2.x-p1.x),len=Math.max(9,w/55);ctx.beginPath();ctx.moveTo(p2.x,p2.y);ctx.lineTo(p2.x-len*Math.cos(ang-.5),p2.y-len*Math.sin(ang-.5));ctx.lineTo(p2.x-len*Math.cos(ang+.5),p2.y-len*Math.sin(ang+.5));ctx.closePath();ctx.fill()}}ctx.restore()}

function apparentDiameterDeg(diameterKm,distanceKm){if(!(diameterKm>0&&distanceKm>0))return 0;return 2*Math.atan(diameterKm/(2*distanceKm))/R}
function angularDiameterPx(deg,s,w,h){if(!(deg>0))return 0;if(s.projection==="allsky"){const rad=Math.min(w,h)*.47;return deg/90*rad}const f=(w/2)/Math.tan(s.camera.fov*R/2);return 2*f*Math.tan(deg*R/2)}
function drawSizedEllipse(ctx,p,majorDeg,minorDeg,s,w,h,dpr,color,alpha,minPx=1,fillAlpha=.10){const maj=Math.max(minPx*dpr,angularDiameterPx(majorDeg,s,w,h)),min=Math.max(minPx*dpr,angularDiameterPx(minorDeg||majorDeg,s,w,h));ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=Math.max(1,dpr);ctx.fillStyle=color;ctx.globalAlpha=alpha*fillAlpha;ctx.beginPath();ctx.ellipse(p.x,p.y,maj/2,min/2,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=alpha;ctx.stroke();ctx.restore()}
function activeMeteorShowers(s){return METEORS.filter(x=>meteorActive(x,s.time))}
function drawMeteorEvents(ctx,s,w,h,dpr){const now=Date.now(),events=s.meteorEvents||[];for(const ev of events){const dur=Math.max(180,Number(ev.duration)||650),t=(now-Number(ev.born||0))/dur;if(t<0||t>1.45)continue;const a=point(ev.p1,s,w,h),b=point(ev.p2,s,w,h);if(!a||!b)continue;const u=clamp(t,0,1),ease=1-Math.pow(1-u,2.35),hx=a.x+(b.x-a.x)*ease,hy=a.y+(b.y-a.y)*ease,dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,nx=dx/len,ny=dy/len,bright=clamp(Number(ev.brightness)||1,.25,2.4),tailFactor=.7+.45*bright,tailLen=Math.min(len,(55+130*bright)*dpr)*tailFactor*(.42+.58*u),tx=hx-nx*tailLen,ty=hy-ny*tailLen,life=t<=1?Math.min(1,t*10):Math.max(0,1-(t-1)/.45),seed=String(ev.id||"").split("").reduce((q,c)=>q+c.charCodeAt(0),0),flick=.91+.07*Math.sin((now-Number(ev.born||0))/31+seed*.17)+.035*Math.sin((now-Number(ev.born||0))/11+seed),rgb=Array.isArray(ev.rgb)&&ev.rgb.length===3?ev.rgb:[235,245,255],core=rgb.map(v=>Math.round(v+(255-v)*.72)),trail=rgb.map(v=>Math.round(v*.82+28)),grad=ctx.createLinearGradient(tx,ty,hx,hy);grad.addColorStop(0,`rgba(${trail.join(',')},0)`);grad.addColorStop(.42,`rgba(${trail.join(',')},${.09*life})`);grad.addColorStop(.82,`rgba(${rgb.join(',')},${Math.min(.58,.28*bright)*life})`);grad.addColorStop(.965,`rgba(${core.join(',')},${Math.min(1,.78*bright*flick)*life})`);grad.addColorStop(1,`rgba(255,255,255,${Math.min(1,bright*flick)*life})`);ctx.save();ctx.globalCompositeOperation="screen";ctx.strokeStyle=grad;ctx.lineWidth=(.65+1.05*bright)*dpr;ctx.shadowColor=`rgba(${rgb.join(',')},${.45+.22*Math.min(1,bright)})`;ctx.shadowBlur=(3+5*bright)*dpr;ctx.beginPath();ctx.moveTo(tx,ty);ctx.lineTo(hx,hy);ctx.stroke();if(bright>1.15){ctx.strokeStyle=`rgba(255,255,255,${.26*life})`;ctx.lineWidth=.45*dpr;ctx.shadowBlur=2*dpr;ctx.beginPath();ctx.moveTo(hx-nx*Math.min(tailLen*.42,45*dpr),hy-ny*Math.min(tailLen*.42,45*dpr));ctx.lineTo(hx,hy);ctx.stroke()}ctx.fillStyle=`rgba(${core.join(',')},${Math.min(1,life*bright*flick)})`;ctx.shadowColor=`rgba(${rgb.join(',')},.95)`;ctx.shadowBlur=(4+4*bright)*dpr;ctx.beginPath();ctx.arc(hx,hy,(.55+.62*bright)*dpr,0,Math.PI*2);ctx.fill();ctx.restore()}}
function drawAltAzGrid(ctx,s,w,h,dpr){ctx.save();ctx.strokeStyle="rgba(167,139,250,.32)";ctx.lineWidth=.8*dpr;for(let alt=0;alt<=80;alt+=10){let prev=null;for(let az=0;az<=360;az+=2){const p=projectRaw(az,alt,s,w,h);if(p&&prev&&Math.hypot(p.x-prev.x,p.y-prev.y)<w*.2){ctx.beginPath();ctx.moveTo(prev.x,prev.y);ctx.lineTo(p.x,p.y);ctx.stroke()}prev=p}}for(let az=0;az<360;az+=15){let prev=null;for(let alt=0;alt<=90;alt+=2){const p=projectRaw(az,alt,s,w,h);if(p&&prev&&Math.hypot(p.x-prev.x,p.y-prev.y)<h*.25){ctx.beginPath();ctx.moveTo(prev.x,prev.y);ctx.lineTo(p.x,p.y);ctx.stroke()}prev=p}}ctx.restore()}
function drawRaDecGrid(ctx,s,w,h,dpr){ctx.save();ctx.strokeStyle="rgba(135,95,205,.34)";ctx.lineWidth=.8*dpr;for(let dec=-60;dec<=75;dec+=15){let prev=null;for(let ra=0;ra<=360;ra+=2){const p=point({ra,dec},s,w,h);if(p&&prev&&Math.hypot(p.x-prev.x,p.y-prev.y)<w*.2){ctx.beginPath();ctx.moveTo(prev.x,prev.y);ctx.lineTo(p.x,p.y);ctx.stroke()}prev=p}}for(let ra=0;ra<360;ra+=15){let prev=null;for(let dec=-75;dec<=75;dec+=2){const p=point({ra,dec},s,w,h);if(p&&prev&&Math.hypot(p.x-prev.x,p.y-prev.y)<h*.25){ctx.beginPath();ctx.moveTo(prev.x,prev.y);ctx.lineTo(p.x,p.y);ctx.stroke()}prev=p}}ctx.restore()}
function horizonPoints(s,w,h){const pts=[];for(let az=0;az<360;az+=1){const p=projectRaw(az,0,s,w,h);if(p&&p.x>-w*.25&&p.x<w*1.25&&p.y>-h&&p.y<h*2)pts.push(p)}pts.sort((a,b)=>a.x-b.x);return pts.filter((p,i)=>i===0||Math.abs(p.x-pts[i-1].x)>1)}function drawGround(ctx,s,w,h,dpr){const pts=horizonPoints(s,w,h);if(pts.length>2){ctx.fillStyle="rgba(2,4,7,.97)";ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(const p of pts.slice(1))ctx.lineTo(p.x,p.y);ctx.lineTo(pts[pts.length-1].x,h);ctx.lineTo(pts[0].x,h);ctx.closePath();ctx.fill();ctx.strokeStyle="rgba(120,190,175,.8)";ctx.lineWidth=1.2*dpr;ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(const p of pts.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke()}}
// Milky Way: immersive low-resolution luminance layer.
// Position follows the Galactic plane, but fine structure is deliberately artistic rather than catalog-bound.
let MILKY_CLOUDS=null, MILKY_LAYER=null, MILKY_SPRITES=null;
function galToEq(lDeg,bDeg){const l=lDeg*R,b=bDeg*R,cb=Math.cos(b),xg=cb*Math.cos(l),yg=cb*Math.sin(l),zg=Math.sin(b),x=-.0548755604*xg+.4941094279*yg-.8676661490*zg,y=-.8734370902*xg-.4448296300*yg-.1980763734*zg,z=-.4838350155*xg+.7469822445*yg+.4559837762*zg;return{ra:norm(Math.atan2(y,x)/R),dec:Math.asin(clamp(z,-1,1))/R}}
function seeded01(n){const x=Math.sin(n*12.9898+78.233)*43758.5453;return x-Math.floor(x)}
function angDist360(a,b){let d=Math.abs(norm(a)-norm(b));return d>180?360-d:d}
function buildMilkyWayClouds(){if(MILKY_CLOUDS)return MILKY_CLOUDS;const out=[];let k=1;for(let l=0;l<360;l+=5){const gc=Math.exp(-Math.pow(angDist360(l,0)/48,2)),cyg=.45*Math.exp(-Math.pow(angDist360(l,78)/38,2)),base=.45+1.18*gc+cyg;const bands=[-7.5,-3.0,3.2,7.8];for(let j=0;j<bands.length;j++,k++){const r1=seeded01(k),r2=seeded01(k+311),r3=seeded01(k+977),b=bands[j]+(r1-.5)*(j===1||j===2?3.1:4.8),eq=galToEq(l+(r2-.5)*4.2,b),lane=Math.exp(-Math.pow(b/2.2,2)),a=(.040+.055*r3)*base*(1-.48*lane),size=5.5+8.5*r2+5*gc;out.push({...eq,a:clamp(a,.018,.19),size})}if(l%10===0){const r1=seeded01(k+1901),r2=seeded01(k+2309),b=(r1-.5)*22,eq=galToEq(l+(r2-.5)*7,b);out.push({...eq,a:(.014+.026*r2)*(.8+.6*gc),size:12+9*r1})}}MILKY_CLOUDS=out;return out}
function makeMilkySprite(size=64){const c=document.createElement("canvas");c.width=c.height=size;const x=c.getContext("2d"),r=size/2,g=x.createRadialGradient(r,r,0,r,r,r);g.addColorStop(0,"rgba(239,235,220,.72)");g.addColorStop(.24,"rgba(220,218,207,.34)");g.addColorStop(.62,"rgba(190,193,190,.105)");g.addColorStop(1,"rgba(175,181,182,0)");x.fillStyle=g;x.fillRect(0,0,size,size);return c}
function milkySprites(){if(!MILKY_SPRITES)MILKY_SPRITES=[makeMilkySprite(48),makeMilkySprite(64),makeMilkySprite(80)];return MILKY_SPRITES}
function ensureMilkyLayer(w,h){const maxW=820,maxH=500,sc=Math.min(1,maxW/Math.max(1,w),maxH/Math.max(1,h)),lw=Math.max(320,Math.round(w*sc)),lh=Math.max(180,Math.round(h*sc));if(!MILKY_LAYER)MILKY_LAYER=document.createElement("canvas");if(MILKY_LAYER.width!==lw||MILKY_LAYER.height!==lh){MILKY_LAYER.width=lw;MILKY_LAYER.height=lh}return MILKY_LAYER}
function milkyPoint(q,s,w,h){if(FRAME_ASTRO){const hv=fastHorizontal(starVec(q));if(!hv||hv.u<-.01)return null;const alt=Math.asin(clamp(hv.u,-1,1))/R,aa=apparentAlt(alt);if(s.projection==="allsky"&&aa<0)return null;const az=norm(Math.atan2(hv.e,hv.n)/R);return projectRaw(az,aa,s,w,h)}return point(q,s,w,h)}
function drawMilkyWay(ctx,s,w,h,dpr,alpha=1){if(alpha<=0)return;const clouds=buildMilkyWayClouds(),layer=ensureMilkyLayer(w,h),lc=layer.getContext("2d"),lw=layer.width,lh=layer.height,sprites=milkySprites(),brightness=clamp(Number(s.display?.milkyWayBrightness)||1,.25,2);lc.clearRect(0,0,lw,lh);lc.save();lc.globalCompositeOperation="screen";for(let i=0;i<clouds.length;i++){const q=clouds[i],p=milkyPoint(q,s,lw,lh);if(!p||p.x<-80||p.x>lw+80||p.y<-80||p.y>lh+80)continue;const sizePx=Math.max(7,angularDiameterPx(q.size,s,lw,lh)),sp=sprites[i%3];lc.globalAlpha=clamp(q.a*brightness,0,.28);lc.drawImage(sp,p.x-sizePx/2,p.y-sizePx/2,sizePx,sizePx)}lc.restore();ctx.save();ctx.globalCompositeOperation="screen";ctx.globalAlpha=clamp(alpha,0,1);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.drawImage(layer,0,0,w,h);ctx.restore()}
function drawMilkyWaySimple(ctx,s,w,h,dpr,alpha=1){if(alpha<=0)return;ctx.save();ctx.globalCompositeOperation="screen";ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle=`rgba(194,198,194,${.10*alpha})`;ctx.lineWidth=12*dpr;let prev=null;ctx.beginPath();for(let l=0;l<=360;l+=5){const p=milkyPoint(galToEq(l%360,0),s,w,h);if(!p){prev=null;continue}if(!prev||Math.hypot(p.x-prev.x,p.y-prev.y)>w*.26)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);prev=p}ctx.stroke();ctx.restore()}
const AU_KEYS={abs:[20,35,45,55,65,75],D:[1500,1200,900,480,170,70],h0:[260,210,150,105,105,105],len:[420,380,330,190,150,140],gW:[.0,.04,.14,.72,.95,1],rW:[1,1,.98,.5,.3,.25],span:[55,70,85,105,135,150],act:[.35,.45,.6,.85,1,1]};
function auInterp(arr,x){const k=AU_KEYS.abs;if(x<=k[0])return arr[0];for(let i=1;i<k.length;i++)if(x<=k[i]){const t=(x-k[i-1])/(k[i]-k[i-1]);return arr[i-1]+(arr[i]-arr[i-1])*t}return arr[arr.length-1]}
function auHash(n){const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x)}
function auNoise(x){const i=Math.floor(x),f=x-i,u=f*f*(3-2*f);return auHash(i)*(1-u)+auHash(i+1)*u}
function auFbm(x){return .55*auNoise(x)+.3*auNoise(x*2.13+7.3)+.15*auNoise(x*4.31+1.7)}
function auSm(a,b,x){const t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t)}
function auStops(gW,rW){
 const G=[70,255,150],G0=[205,255,228],PK=[255,95,195],RD=[255,42,58],VI=[125,105,255],rb=Math.max(0,Math.min(1,rW-gW)),rt=Math.min(rW,gW)*.5,pk=.55;
 const us=[0,.02,.05,.1,.18,.3,.45,.6,.75,.88,1],out=[];
 for(const u of us){
  const ag=gW*(u<.04?auSm(0,.04,u):Math.exp(-(u-.04)*2.1)),w0=Math.exp(-u*14)*.32,ap=gW*pk*Math.exp(-Math.pow((u-.012)/.03,2))*.55;
  const ar=rb*auSm(0,.05,u)*Math.exp(-Math.max(0,u-.05)*1.6)*.85+rt*auSm(.4,.82,u)*(1-auSm(.86,1,u))*1.0,av=gW*.16*auSm(.62,.92,u)*(1-auSm(.93,1,u));
  const sum=ag+ap+ar+av,end=1-auSm(.42,1,u);
  if(sum<=1e-4){out.push([u,0,0,0,0]);continue}
  const gc=[G[0]+(G0[0]-G[0])*w0,G[1]+(G0[1]-G[1])*w0,G[2]+(G0[2]-G[2])*w0];
  out.push([u,Math.round((ag*gc[0]+ap*PK[0]+ar*RD[0]+av*VI[0])/sum),Math.round((ag*gc[1]+ap*PK[1]+ar*RD[1]+av*VI[1])/sum),Math.round((ag*gc[2]+ap*PK[2]+ar*RD[2]+av*VI[2])/sum),Math.min(1,sum*(1+rb*.9))*end])
 }
 return out
}
function drawAurora(ctx,s,w,h,dpr,alpha=1,night=1,quality=1){
 if(alpha<=0||night<=0)return;
 const intensity=Math.max(0,Math.min(2,Number(s.global?.auroraIntensity)||1));if(intensity<=0)return;
 quality*=Math.max(.55,Math.min(1,Math.sqrt(2.4e6/(w*h))));
 const lat=Number(s.location?.lat)||0,abs=Math.min(90,Math.abs(lat)),pole=lat<0?-1:1,poleAz=lat<0?180:0,all=s.projection==="allsky";
 const D0=auInterp(AU_KEYS.D,abs),h0=auInterp(AU_KEYS.h0,abs),len=auInterp(AU_KEYS.len,abs),gW=auInterp(AU_KEYS.gW,abs),rW=auInterp(AU_KEYS.rW,abs),span=auInterp(AU_KEYS.span,abs),act=auInterp(AU_KEYS.act,abs);
 const dip=Math.atan(2*Math.tan(abs*.92*R)),cd=Math.cos(dip),sd=Math.sin(dip),latF=Math.max(.2,Math.min(1,(abs-25)/45));
 const A=alpha*night*intensity*(.5+.5*latF)*(.62+.38*act),T=performance.now()/1000;
 const fpx=all?Math.min(w,h)*.47/90:((w/2)/Math.tan(s.camera.fov*R/2))*R,altRef=Math.atan2(h0,D0)/R;
 const vf=all?90:Math.atan(Math.tan(s.camera.fov*R/2)*h/w)/R;
 let lo=-span/2,hi=span/2;
 if(!all&&s.camera.alt+vf<76){let ac=norm(s.camera.az-poleAz);if(ac>180)ac-=360;ac*=pole;const half=(s.camera.fov/2)/Math.cos(Math.min(78,Math.max(0,s.camera.alt+vf))*R)*1.12+4;lo=Math.max(lo,ac-half);hi=Math.min(hi,ac+half)}
 if(hi<=lo)return;
 const rbal=Math.max(0,Math.min(1,rW-gW)),rimC=[Math.round(170+85*rbal),Math.round(255-105*rbal),Math.round(215-50*rbal)],glC=[Math.round(110+145*rbal),Math.round(255-175*rbal),Math.round(170-100*rbal)],stops=auStops(gW,rW),curtains=[{dm:1,al:1,cap:Math.round(720*quality),ln:1,seed:0}];
 if(abs>=30)curtains.push({dm:1.22,al:.5,cap:Math.round(300*quality),ln:.8,seed:1});
 if(abs>=50)curtains.push({dm:1.55,al:.34,cap:Math.round(200*quality),ln:.7,seed:2});
 ctx.save();ctx.globalCompositeOperation="lighter";ctx.lineCap="butt";
 {const pc=projectRaw(norm(poleAz),Math.max(2,altRef*.8),s,w,h);
  if(pc){const rx=Math.min(w*.9,fpx*span*.42),ry=Math.min(h*.7,fpx*(altRef+25)),gA=.06*A*(.5+.5*act),g=ctx.createRadialGradient(0,0,0,0,0,1),rr=Math.round(255*Math.min(1,rW*.9+.1)),gg=Math.round(255*Math.min(1,gW+.12));
   ctx.save();ctx.translate(pc.x,pc.y);ctx.scale(rx,ry);const rg=ctx.createRadialGradient(0,0,0,0,0,1);rg.addColorStop(0,`rgba(${rr*(rW>gW?1:.35)|0},${gg*(gW>=rW?1:.28)|0},${gW>=rW?110:70},${gA})`);rg.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=rg;ctx.fillRect(-1,-1,2,2);ctx.restore()}}
 for(let c=0;c<curtains.length;c++){
  const cu=curtains[c],ph=cu.seed*3.7+.6,da=Math.max((hi-lo)/cu.cap,Math.min(1,2.3*dpr/(fpx*Math.max(.3,Math.cos(altRef*R))))*(c?1.6:1));
  let prev=null,idx=0;const rim=[];
  for(let a=lo;a<=hi;a+=da,idx++){
   const ar=a*R,ca=Math.cos(ar),x=ar;
   const pat=auSm(.26,.8,auFbm(a*.05+cu.seed*13.1+T*.012+2.5)),edge=Math.pow(Math.max(0,Math.cos(Math.PI*a/(span*1.04))),.6);
   const fine=(.42+.58*auNoise(a*2.7+T*.4+cu.seed*5.3))*(.65+.35*auNoise(a*7.1-T*.6+cu.seed)),puls=.78+.22*Math.sin(T*(.55+.12*c)+a*.045+c),flick=.9+.1*auNoise(T*4+a*1.3);
   const B=edge*(.16+.84*pat)*fine*puls*flick*cu.al;if(B<.025){prev=null;continue}
   const fold=1+.11*Math.sin(x*2.3+ph+T*.045+1.3*Math.sin(x*1.1+T*.03))+.06*Math.sin(x*5.2-ph*1.7-T*.09)+.025*Math.sin(x*11+T*.17),Dc=cu.dm*D0*fold,E=Dc*Math.tan(ar);
   const hb=h0*(1+.05*auNoise(a*.9+T*.08+cu.seed)),Lr=len*cu.ln*(.62+.55*auNoise(a*.17+T*.08+cu.seed*9.1))*(.62+.5*pat)*(.93+.14*auNoise(a*1.9+T*.25));
   const alt0=Math.atan2(hb,Dc/ca)/R,azw0=norm(poleAz+pole*a),p1=projectRaw(azw0,alt0,s,w,h);if(!p1){prev=null;continue}
   let p2=null,pm=null,f=1;
   for(let k=0;k<3&&!p2;k++,f*=.6){const Lk=Lr*f,N2=Dc-cd*Lk,U2=hb+sd*Lk,az2=Math.atan2(E,N2)/R,al2=Math.atan2(U2,Math.hypot(E,N2))/R,Nm=Dc-cd*Lk*.5,Um=hb+sd*Lk*.5,azm=Math.atan2(E,Nm)/R,alm=Math.atan2(Um,Math.hypot(E,Nm))/R;
    p2=projectRaw(norm(poleAz+pole*az2),al2,s,w,h);pm=projectRaw(norm(poleAz+pole*azm),alm,s,w,h)}
   if(!p2||!pm){prev=null;continue}
   const m=w*.25;if((p1.x<-m&&p2.x<-m)||(p1.x>w+m&&p2.x>w+m)||(p1.y<-m&&p2.y<-m)||(p1.y>h+m&&p2.y>h+m)){prev=null;continue}
   let sp=prev?Math.hypot(p1.x-prev.x,p1.y-prev.y):0;if(!(sp>0&&sp<60*dpr))sp=2.3*dpr;prev=p1;
   const hz=.25+.75*auSm(.2,5,alt0),lw=Math.max(1.3*dpr,sp*1.75)*(.85+.3*auHash(idx*1.37+c)),k=B*A*hz*1.15;
   const gr=ctx.createLinearGradient(p1.x,p1.y,p2.x,p2.y);for(const st of stops)gr.addColorStop(st[0],`rgba(${st[1]},${st[2]},${st[3]},${Math.min(1,st[4]*k).toFixed(3)})`);
   ctx.strokeStyle=gr;ctx.lineWidth=lw;ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.quadraticCurveTo(2*pm.x-(p1.x+p2.x)/2,2*pm.y-(p1.y+p2.y)/2,p2.x,p2.y);ctx.stroke();
   if(idx%2===0){ctx.globalAlpha=.15;ctx.lineWidth=lw*6;ctx.stroke();ctx.globalAlpha=1}
   if(c===0)rim.push(p1.x,p1.y,Math.min(1,k),sp)
  }
  for(let i=4;i<rim.length;i+=4){const x0=rim[i-4],y0=rim[i-3],x1=rim[i],y1=rim[i+1],d=Math.hypot(x1-x0,y1-y0);if(d>rim[i+3]*3.5+4*dpr)continue;const al=Math.min(1,(rim[i-2]+rim[i+2])*.5);ctx.strokeStyle=`rgba(${rimC[0]},${rimC[1]},${rimC[2]},${(al*.38).toFixed(3)})`;ctx.lineWidth=2.4*dpr;ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(x1,y1);ctx.stroke();ctx.strokeStyle=`rgba(${glC[0]},${glC[1]},${glC[2]},${(al*.12).toFixed(3)})`;ctx.lineWidth=10*dpr;ctx.stroke()}
 }
 ctx.restore();
}
function skyText(ctx,s,w,h,p,text,dx=0,dy=0){if(!p)return;if(s.projection!=="allsky"){ctx.fillText(text,p.x+dx,p.y+dy);return}const a=Math.atan2(p.y-h/2,p.x-w/2)-Math.PI/2;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a);ctx.fillText(text,dx,dy);ctx.restore()}
function drawCompass(ctx,s,w,h,dpr,display,fontFamily="sans-serif"){
 ctx.save();ctx.shadowColor="rgba(0,0,0,.95)";ctx.shadowBlur=4*dpr;
 const hs=display?.hudTextScale||4,pp=n=>String(n).padStart(2,"0"),d=s.time,da=fade("global:direction",!!s.global.direction),ta=fade("global:time",!!s.global.time),ca=fade("global:coordinates",!!s.global.coordinates),dirPx=12*hs,timePx=8*hs,pad=10*dpr;
 const dirFont=`700 ${dirPx*dpr}px ${fontFamily}`,timeFont=`${timePx*dpr}px ${fontFamily}`,coordFont=`${Math.max(5.5,6.6*hs)*dpr}px ${fontFamily}`;
 let timeX=w/2,timeY=h-pad;
 if(s.projection==="perspective"){
   const dirY=h-pad;
   if(da>0){ctx.globalAlpha=da;const span=s.camera.fov*.42;ctx.textAlign="center";ctx.fillStyle="#eef6ff";ctx.font=dirFont;ctx.fillText(`${dir16(s.camera.az)}（${Math.round(s.camera.az)}°）`,w/2,dirY);ctx.fillStyle="#9fb5c8";ctx.font=`${8*hs*dpr}px ${fontFamily}`;ctx.textAlign="left";ctx.fillText(dir16(s.camera.az-span),pad,dirY);ctx.textAlign="right";ctx.fillText(dir16(s.camera.az+span),w-pad,dirY)}
   ctx.font=dirFont;const dm=ctx.measureText(`${dir16(s.camera.az)}（${Math.round(s.camera.az)}°）`),dirH=(dm.actualBoundingBoxAscent||dirPx*dpr*.8)+(dm.actualBoundingBoxDescent||dirPx*dpr*.2);
   ctx.font=timeFont;const tm=ctx.measureText("00:00:00"),timeH=(tm.actualBoundingBoxAscent||timePx*dpr*.8)+(tm.actualBoundingBoxDescent||timePx*dpr*.2);
   timeY=Math.max(timeH+pad,dirY-dirH-Math.max(6*dpr,timeH*.35));
 }else{
   const south=projectRaw(180,0,s,w,h),southY=south?.y??h*.95;
   if(da>0){ctx.globalAlpha=da;ctx.fillStyle="#eef6ff";ctx.font=`700 ${9*hs*dpr}px ${fontFamily}`;ctx.textAlign="center";for(const[t,a]of [["北",0],["東",90],["南",180],["西",270]]){const p=projectRaw(a,0,s,w,h);skyText(ctx,s,w,h,p,t,0,0)}}
   const southFontPx=9*hs*dpr;ctx.font=`700 ${southFontPx}px ${fontFamily}`;const dm=ctx.measureText("南"),dirH=(dm.actualBoundingBoxAscent||southFontPx*.8)+(dm.actualBoundingBoxDescent||southFontPx*.2);
   ctx.font=timeFont;const tm=ctx.measureText("00:00:00"),timeH=(tm.actualBoundingBoxAscent||timePx*dpr*.8)+(tm.actualBoundingBoxDescent||timePx*dpr*.2);
   timeX=south?.x??w/2;timeY=Math.max(timeH+pad,southY-dirH-Math.max(6*dpr,timeH*.35));
 }
 const lat=Number(s.location?.lat)||0,lon=Number(s.location?.lon)||0,latTxt=`${Math.abs(lat).toFixed(2)}°${lat>=0?"N":"S"}`,lonTxt=`${Math.abs(lon).toFixed(2)}°${lon>=0?"E":"W"}`,coordText=`${latTxt}  ${lonTxt}`,timeText=`${pp(d.getHours())}:${pp(d.getMinutes())}:${pp(d.getSeconds())}`;
 if(ta>0&&ca>0){ctx.font=timeFont;const tw=ctx.measureText(timeText).width;ctx.font=coordFont;const cw=ctx.measureText(coordText).width,gap=Math.max(9*dpr,4*hs*dpr),left=timeX-(tw+gap+cw)/2;ctx.globalAlpha=ta;ctx.textAlign="left";ctx.fillStyle="#c1d1df";ctx.font=timeFont;ctx.fillText(timeText,left,timeY);ctx.globalAlpha=ca;ctx.fillStyle="#9fb5c8";ctx.font=coordFont;ctx.fillText(coordText,left+tw+gap,timeY)}
 else if(ta>0){ctx.globalAlpha=ta;ctx.textAlign="center";ctx.fillStyle="#c1d1df";ctx.font=timeFont;ctx.fillText(timeText,timeX,timeY)}
 else if(ca>0){ctx.globalAlpha=ca;ctx.textAlign="center";ctx.fillStyle="#9fb5c8";ctx.font=coordFont;ctx.fillText(coordText,timeX,timeY)}
 ctx.restore()
}
const ATMOS_CACHE={canvas:null,key:""};
function ensureAtmosLayer(w,h){const maxW=640,maxH=360,sc=Math.min(1,maxW/Math.max(1,w),maxH/Math.max(1,h)),lw=Math.max(160,Math.round(w*sc)),lh=Math.max(90,Math.round(h*sc));if(!ATMOS_CACHE.canvas||ATMOS_CACHE.canvas.width!==lw||ATMOS_CACHE.canvas.height!==lh){ATMOS_CACHE.canvas=document.createElement("canvas");ATMOS_CACHE.canvas.width=lw;ATMOS_CACHE.canvas.height=lh;ATMOS_CACHE.key=""}return ATMOS_CACHE.canvas}
function qn(v,step){return Math.round(Number(v||0)/step)*step}
function drawAtmosphereLight(ctx,s,w,h,dayA,su,suaa,moonLightA,mo,mp,effectiveSunAlt){const layer=ensureAtmosLayer(w,h),lc=layer.getContext("2d"),lw=layer.width,lh=layer.height;const sp=dayA>0&&suaa.alt>-18?point(su,s,w,h):null;let ml=0,ma=null;if(moonLightA>0&&mp){ma=altaz(mo.ra,mo.dec,s.time,s.location.lat,s.location.lon);const night=smooth01(clamp((-effectiveSunAlt-2)/10,0,1)),above=smooth01(clamp(ma.alt/8,0,1));ml=moonLightA*night*above}const sx=sp?sp.x/w*lw:-999,sy=sp?sp.y/h*lh:-999,mx=mp?mp.x/w*lw:-999,my=mp?mp.y/h*lh:-999;const key=[lw,lh,s.projection,qn(dayA,.025),qn(suaa.alt,.35),qn(sx,6),qn(sy,6),qn(ml,.025),qn(mx,6),qn(my,6)].join("|");if(key!==ATMOS_CACHE.key){ATMOS_CACHE.key=key;lc.clearRect(0,0,lw,lh);lc.save();lc.globalCompositeOperation="source-over";if(sp&&dayA>.001){const r=Math.max(lw,lh)*.55,g=lc.createRadialGradient(sx,sy,0,sx,sy,r);g.addColorStop(0,`rgba(255,205,145,${.34*dayA})`);g.addColorStop(.55,`rgba(120,185,235,${.12*dayA})`);g.addColorStop(1,"rgba(80,150,220,0)");lc.fillStyle=g;lc.fillRect(0,0,lw,lh)}if(mp&&ml>.001){const r=Math.max(lw,lh)*.42,g=lc.createRadialGradient(mx,my,0,mx,my,r);g.addColorStop(0,`rgba(205,220,238,${.20*ml})`);g.addColorStop(.5,`rgba(130,155,190,${.07*ml})`);g.addColorStop(1,"rgba(70,100,140,0)");lc.fillStyle=g;lc.fillRect(0,0,lw,lh)}lc.restore()}ctx.save();ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="low";ctx.drawImage(layer,0,0,w,h);ctx.restore()}
const FAST_STAR_CACHE=new WeakMap();function starVec(st){let v=FAST_STAR_CACHE.get(st);if(v)return v;const ra=Number(st.ra)*R,de=Number(st.dec)*R,cd=Math.cos(de);v={x:cd*Math.cos(ra),y:cd*Math.sin(ra),z:Math.sin(de),mag:Number(st.mag),id:st.id||"",col:st.display_color_hex?hexToRgb(st.display_color_hex):bvColor(Number(st.bv))};FAST_STAR_CACHE.set(st,v);return v}function fastHorizontal(v){const f=FRAME_ASTRO;if(!f)return null;const ch=f.cosLst*v.x+f.sinLst*v.y,sh=f.sinLst*v.x-f.cosLst*v.y,n=v.z*f.cosLat-ch*f.sinLat,e=-sh,u=v.z*f.sinLat+ch*f.cosLat;return{n,e,u}}
function drawStarField(ctx,s,w,h,dpr,sunAlt,layerAlpha=1,moonPenalty=0,display){if(layerAlpha<=0)return;const now=performance.now(),base=ONLINE_STARS.length?ONLINE_STARS:D.stars,extra=Object.values(USER_STARS).filter(st=>ONLINE_STARS.length?!ONLINE_STAR_BY_ID[st.id]:!S[st.id]),arr=extra.length?[...base,...extra]:base,all=s.projection==="allsky",f=FRAME_ASTRO,rad=Math.min(w,h)*.47,starScale=display?.starScale||4,magLim=effectiveStarMagLimit(s),fastMagLim=Math.min(magLim,limitingMag(sunAlt,magLim)-moonPenalty+1.55);for(const st of arr){const v=starVec(st);if(v.mag>fastMagLim)continue;let p,alt;if(f){const q=fastHorizontal(v);if(!q||q.u<-.02)continue;alt=Math.asin(clamp(q.u,-1,1))/R;const aa=apparentAlt(alt);if(all){if(aa<0)continue;const den=Math.max(1e-7,Math.hypot(q.n,q.e)),rr=(90-aa)/90*rad;p={x:w/2-rr*(q.e/den),y:h/2-rr*(q.n/den),z:1}}else{const az=norm(Math.atan2(q.e,q.n)/R);p=projectRaw(az,aa,s,w,h);if(!p)continue}}else{const aa=altaz(st.ra,st.dec,s.time,s.location.lat,s.location.lon);alt=aa.alt;if(alt<-.8)continue;p=projectRaw(aa.az,apparentAlt(alt),s,w,h);if(!p)continue}if(!inside(p,w,h,3))continue;let col=v.col;const warm=clamp((18-alt)/42,0,.20);if(warm>0)col=mix(col,[255,185,135],warm);const starBrightness=Math.max(.25,Math.min(2.5,Number(display?.starBrightness)||1)),a=Math.min(1,layerAlpha*starBrightness*starAlpha(v.mag,alt,sunAlt,v.id,now,magLim,moonPenalty,!!s.global.scintillation,s.global.scintillationStrength));if(a<.004)continue;ctx.fillStyle=`rgba(${col[0]},${col[1]},${col[2]},${a})`;const rr=.72*starScale*dpr;if(all&&v.mag>2.5){const z=Math.max(1,rr*.72);ctx.fillRect(p.x-z*.5,p.y-z*.5,z,z)}else{ctx.beginPath();ctx.arc(p.x,p.y,rr,0,Math.PI*2);ctx.fill();if(v.mag<1.2&&a>.28){ctx.fillStyle=`rgba(${col[0]},${col[1]},${col[2]},${a*.18})`;ctx.beginPath();ctx.arc(p.x,p.y,1.45*starScale*dpr,0,Math.PI*2);ctx.fill()}}}}

const NATURAL_DSO_EXTRA=[
{id:"LMC",name:"大マゼラン雲",ra:80.8942,dec:-69.7561,mag:.9,type:"galaxy",major:10.5,minor:8.0},
{id:"SMC",name:"小マゼラン雲",ra:13.1867,dec:-72.8286,mag:2.7,type:"galaxy",major:5.2,minor:3.2},
{id:"NGC5139",name:"ω星団",ra:201.697,dec:-47.4795,mag:3.7,type:"cluster",major:.60,minor:.60},
{id:"NGC104",name:"47 Tuc",ra:6.0236,dec:-72.0813,mag:4.1,type:"cluster",major:.52,minor:.52}
];
function naturalDsoObjects(){const out=[];for(const o of D.dsos||[]){const mag=Number(o.magnitude_v??o.mag);if(!Number.isFinite(mag)||mag>6.25)continue;const pos=o.position&&Number.isFinite(Number(o.position.ra_deg))?{ra:+o.position.ra_deg,dec:+o.position.dec_deg}:{ra:+o.ra,dec:+o.dec};if(!Number.isFinite(pos.ra)||!Number.isFinite(pos.dec))continue;const a=o.angular_size||{},maj=Number(a.major_arcmin)/60,min=Number(a.minor_arcmin)/60;if(!(maj>0))continue;out.push({id:o.id,name:typeof o.name==="object"?(o.name.ja||o.name.en||o.id):(o.display_name||o.name||o.id),ra:pos.ra,dec:pos.dec,mag,type:o.type||"dso",major:maj,minor:min>0?min:maj})}return out.concat(NATURAL_DSO_EXTRA)}
function drawNaturalDeepSky(ctx,s,w,h,dpr,alpha=1){if(alpha<=0||s.global?.naturalDeepSky===false)return;const su=sun(jd(s.time)),sa=altaz(su.ra,su.dec,s.time,s.location.lat,s.location.lon),night=smooth01(clamp((-sa.alt-5)/12,0,1));if(night<=.01)return;ctx.save();ctx.globalCompositeOperation="screen";for(const o of naturalDsoObjects()){const p=point(o,s,w,h);if(!p)continue;const maj=Math.max(1.5,angularDiameterPx(o.major,s,w,h)),min=Math.max(1,angularDiameterPx(o.minor||o.major,s,w,h)),surface=Math.max(.1,Math.min(1,Math.pow(10,-.12*(Number(o.mag||6)-2.5)))),a=clamp(alpha*night*(.045+.17*surface),0,.24);let c=[215,220,210];if(o.type==="nebula")c=[170,210,185];else if(o.type==="cluster"||o.type==="star_cloud")c=[230,226,205];const g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,maj/2);g.addColorStop(0,`rgba(${c.join(",")},${a})`);g.addColorStop(.45,`rgba(${c.join(",")},${a*.55})`);g.addColorStop(1,`rgba(${c.join(",")},0)`);ctx.save();ctx.translate(p.x,p.y);ctx.scale(1,Math.max(.08,min/maj));ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,maj/2,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.restore()}
function cometPositions(s){const out=[];for(const c of NIGHT_COMETS){const ep=interpolateEphemeris(c.points,s.time);if(ep)out.push({...c,...ep})}return out}function meteorActive(m,date){const x=str=>{if(!str)return null;const[a,b,c]=str.split("-").map(Number);return new Date(a,b-1,c,12)};const st=x(m.activeStart),en=x(m.activeEnd),d=new Date(date);d.setHours(12,0,0,0);return st&&en&&d>=st&&d<=en}
function render(canvas,s,drawAnn=true,opts={}){
 const fontFamily=opts.projector?`"Yu Mincho","Hiragino Mincho ProN","Hiragino Mincho Pro","Noto Serif JP",serif`:"sans-serif";
 const display=opts.preview?{starScale:1.5,objectTextScale:1.6,constellationTextScale:1.6,hudTextScale:1.6}:(s.display||{starScale:5,objectTextScale:4,constellationTextScale:4,hudTextScale:4});
 const ctx=canvas.getContext("2d"),nativeDpr=Math.max(1,Math.min(2,devicePixelRatio||1)),dprScale=Number.isFinite(Number(opts.dprScale))?clamp(Number(opts.dprScale),.5,1):null,dprCap=Number.isFinite(Number(opts.dprCap))?Math.max(.45,Number(opts.dprCap)):2,dpr=dprScale!==null?Math.max(1,nativeDpr*dprScale):Math.max(.45,Math.min(dprCap,devicePixelRatio||1)),rect=canvas.getBoundingClientRect(),w=Math.max(240,Math.round(rect.width*dpr)),h=Math.max(135,Math.round(rect.height*dpr));
 if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}
 ctx.clearRect(0,0,w,h);ctx.fillStyle="#000";ctx.fillRect(0,0,w,h);setFrameAstro(s.time,s.location.lat,s.location.lon);
 const su=sun(jd(s.time)),suaa=altaz(su.ra,su.dec,s.time,s.location.lat,s.location.lon),all=s.projection==="allsky",rad=Math.min(w,h)*.47;
 const dayA=fade("global:daylight",!!s.global.daylight),moonLightA=fade("global:moonlight",!!s.global.moonlight),starsA=fade("global:stars",!!s.global.stars);
 const effectiveSunAlt=-30+(suaa.alt+30)*dayA,moonPenalty=moonSkyPenalty(s,effectiveSunAlt)*moonLightA,mo=moon(jd(s.time)),mp=point(mo,s,w,h);
 ctx.save();if(all){ctx.beginPath();ctx.arc(w/2,h/2,rad,0,Math.PI*2);ctx.clip()}
 const night=[0,0,3],day=daylightBase(suaa.alt);ctx.fillStyle=rgb(mix(night,day,dayA));ctx.fillRect(0,0,w,h);
 if(opts.gpuSkyLayer){ctx.save();ctx.globalCompositeOperation="source-over";ctx.drawImage(opts.gpuSkyLayer,0,0,w,h);ctx.restore()}else{drawAtmosphereLight(ctx,s,w,h,dayA,su,suaa,moonLightA,mo,mp,effectiveSunAlt);const mwA=fade("global:milkyWay",!!s.global.milkyWay),mwNight=smooth01(clamp((-effectiveSunAlt-4)/12,0,1)),mwMoon=Math.exp(-1.25*Math.max(0,moonPenalty)),mwVis=mwA*mwNight*mwMoon;if(mwVis>0){if(opts.preview)drawMilkyWaySimple(ctx,s,w,h,dpr,mwVis);else drawMilkyWay(ctx,s,w,h,dpr,mwVis)};drawNaturalDeepSky(ctx,s,w,h,dpr,1)}const auA=fade("global:aurora",!!s.global.aurora);if(auA>0)drawAurora(ctx,s,w,h,dpr,auA,smooth01(clamp((-effectiveSunAlt-5)/9,0,1)),opts.preview?.45:1);
 const aaA=fade("global:altazGrid",!!s.global.altazGrid);if(aaA>0){ctx.save();ctx.globalAlpha=aaA;drawAltAzGrid(ctx,s,w,h,dpr);ctx.restore()}
 const rdA=fade("global:radecGrid",!!s.global.radecGrid);if(rdA>0){ctx.save();ctx.globalAlpha=rdA;drawRaDecGrid(ctx,s,w,h,dpr);ctx.restore()}
 for(const c of D.constellations){const a=fade("line:"+c.id,effectiveConst(s,c.id,"line"));if(a<=0)continue;ctx.strokeStyle=`rgba(105,190,235,${.8*a})`;ctx.lineWidth=1.25*dpr;for(const[u,v]of segmentsFor(c.abbr,s)){const p=point(coordFor(u),s,w,h),q=point(coordFor(v),s,w,h);if(p&&q&&Math.hypot(p.x-q.x,p.y-q.y)<w*.7){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}}
 const userConstellations=Array.isArray(s.customConstellations)?s.customConstellations:[];for(const c of userConstellations){if(!c||c.visible===false)continue;const a=fade("custom-line:"+(c.id||c.name||"user"),true);if(a<=0)continue;ctx.save();ctx.strokeStyle=`rgba(222,164,255,${.9*a})`;ctx.lineWidth=1.7*dpr;for(const sg of(Array.isArray(c.segments)?c.segments:[])){const u=String(sg?.[0]||""),v=String(sg?.[1]||"");if(!u||!v)continue;const p=point(coordFor(u),s,w,h),q=point(coordFor(v),s,w,h);if(p&&q&&Math.hypot(p.x-q.x,p.y-q.y)<w*.75){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}ctx.restore()}
 if(starsA>0&&!opts.gpuSkyLayer){if(opts.starLayer){ctx.save();ctx.globalAlpha=starsA;ctx.drawImage(opts.starLayer,0,0,w,h);ctx.restore()}else if(!opts.skipStars)drawStarField(ctx,s,w,h,dpr,effectiveSunAlt,starsA,moonPenalty,display);}
 const snA=fade("global:starNames",!!s.global.starNames);if(snA>0){ctx.font=`${8*(display.objectTextScale||4)*dpr}px ${fontFamily}`;ctx.textAlign="left";ctx.globalAlpha=snA;for(const st of D.stars){if(Number(st.mag)>Math.min(effectiveStarMagLimit(s),3.3))continue;const p=point(st,s,w,h);if(!p)continue;ctx.fillStyle="#ff9898";skyText(ctx,s,w,h,p,st.display_name||st.name,4*dpr,-3*dpr)}ctx.globalAlpha=1}
 const artEntries=[];for(const c of D.constellations){const p=point(c,s,w,h),a=fade("name:"+c.id,effectiveConst(s,c.id,"name"));if(p&&a>0){ctx.fillStyle=`rgba(150,220,255,${a})`;ctx.font=`${10*(display.constellationTextScale||4)*dpr}px ${fontFamily}`;ctx.textAlign="center";skyText(ctx,s,w,h,p,c.name,0,0)}const artA=fade("art:"+c.id,effectiveConst(s,c.id,"art"));if(artA>.001&&ART[c.id])artEntries.push({id:c.id,alpha:artA})}if(!opts.gpuSkyLayer||!opts.gpuArtsReady)drawConstellationArts(ctx,s,w,h,artEntries,opts);for(const c of userConstellations){if(!c||c.visible===false||c.showName===false)continue;const q=customConstellationCenter(c),p=q?point(q,s,w,h):null,a=fade("custom-name:"+(c.id||c.name||"user"),true);if(!p||a<=0)continue;ctx.save();ctx.globalAlpha=a;ctx.fillStyle="#e6b4ff";ctx.font=`${10*(display.constellationTextScale||4)*dpr}px ${fontFamily}`;ctx.textAlign="center";skyText(ctx,s,w,h,p,c.name||c.abbr||"自作星座",0,-8*dpr);ctx.restore()}
 for(const ast of ASTERISMS){const a=fade("ast:"+ast.id,effectiveAst(s,ast.id));if(a<=0)continue;const strong=s.asterisms[ast.id]===true;ctx.strokeStyle=`rgba(110,205,245,${(strong?.95:.62)*a})`;ctx.lineWidth=(strong?2:1.3)*dpr;for(const[u,v]of ast.lines){const p=point(coordFor(u),s,w,h),q=point(coordFor(v),s,w,h);if(p&&q){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}}
 const dsoA=fade("global:dso",!!s.global.dso),dsoNameA=fade("global:dsoNames",!!s.global.dsoNames);for(const o of D.dsos){if(dsoA<=0&&dsoNameA<=0&&!s.highlights[o.id]&&!s.labels[o.id])continue;const p=point(o,s,w,h);if(!p)continue;if(dsoA>0){const as=o.angular_size||{},maj=Number(as.major_arcmin)/60,min=Number(as.minor_arcmin)/60;if(maj>0)drawSizedEllipse(ctx,p,maj,min||maj,s,w,h,dpr,"#6ee7a6",dsoA,1.2,.07);else{ctx.globalAlpha=dsoA;ctx.strokeStyle="#6ee7a6";ctx.lineWidth=1.2*dpr;ctx.strokeRect(p.x-3*dpr,p.y-3*dpr,6*dpr,6*dpr)}}if(dsoNameA>0){ctx.globalAlpha=dsoNameA;ctx.fillStyle="#9af0bd";ctx.font=`${8*(display.objectTextScale||4)*dpr}px ${fontFamily}`;ctx.textAlign="left";skyText(ctx,s,w,h,p,o.name,5*dpr,-4*dpr)}ctx.globalAlpha=1}
 const sunA=fade("global:sun",!!s.global.sun),sunNameA=fade("global:sunName",!!s.global.sunName);if(sunA>0||sunNameA>0){const p=point(su,s,w,h);if(p){const dia=apparentDiameterDeg(Number(SOLAR.Sun?.physical_diameter_km)||1391400,su.distanceKm||AU_KM),diaPx=Math.max(1.5*dpr,angularDiameterPx(dia,s,w,h));if(sunA>0)drawSizedEllipse(ctx,p,dia,dia,s,w,h,dpr,"#ffd54f",sunA,1.5,.92);if(sunNameA>0){ctx.save();ctx.globalAlpha=sunNameA;ctx.fillStyle="#ffe995";ctx.font=`${8*(display.objectTextScale||4)*dpr}px ${fontFamily}`;ctx.textAlign="left";skyText(ctx,s,w,h,p,"太陽",diaPx*.58+4*dpr,-3*dpr);ctx.restore()}}}
 const ecA=fade("global:ecliptic",!!s.global.ecliptic);if(ecA>0){ctx.strokeStyle=`rgba(255,215,70,${.6*ecA})`;ctx.lineWidth=1*dpr;let pr=null,eps=23.4393*R;for(let l=0;l<=360;l+=3){const lr=l*R,o={ra:norm(Math.atan2(Math.cos(eps)*Math.sin(lr),Math.cos(lr))/R),dec:Math.asin(Math.sin(eps)*Math.sin(lr))/R},p=point(o,s,w,h);if(p&&pr&&Math.hypot(p.x-pr.x,p.y-pr.y)<w*.2){ctx.beginPath();ctx.moveTo(pr.x,pr.y);ctx.lineTo(p.x,p.y);ctx.stroke()}pr=p}}

 const moonA=fade("global:moon",!!s.global.moon),moonNameA=fade("global:moonName",!!s.global.moonName);if((moonA>0||moonNameA>0)&&mp){const dia=apparentDiameterDeg(Number(SOLAR.Moon?.physical_diameter_km)||3475,mo.distanceKm||385000),diaPx=Math.max(1.5*dpr,angularDiameterPx(dia,s,w,h));if(moonA>0)drawSizedEllipse(ctx,mp,dia,dia,s,w,h,dpr,"#e8e8f0",moonA,1.5,.88);if(moonNameA>0){ctx.save();ctx.globalAlpha=moonNameA;ctx.fillStyle="#f0f0f6";ctx.font=`${8*(display.objectTextScale||4)*dpr}px ${fontFamily}`;ctx.textAlign="left";skyText(ctx,s,w,h,mp,"月",diaPx*.58+4*dpr,-3*dpr);ctx.restore()}}
 const lpA=fade("global:lunarPath",!!s.global.lunarPath);if(lpA>0){ctx.strokeStyle=`rgba(210,210,220,${.55*lpA})`;let pr=null;for(let dd=-14;dd<=14;dd++){const m=moon(jd(new Date(s.time.getTime()+dd*864e5))),p=point(m,s,w,h);if(p&&pr){ctx.beginPath();ctx.moveTo(pr.x,pr.y);ctx.lineTo(p.x,p.y);ctx.stroke()}pr=p}}
 const plA=fade("global:planets",!!s.global.planets),plnA=fade("global:planetNames",!!s.global.planetNames);if(plA>0||plnA>0){for(const[id,nm]of Object.entries(PLANET_NAMES)){const po=planet(id,jd(s.time)),p=point(po,s,w,h);if(!p)continue;if(plA>0){const diam=Number(PINFO[id]?.physical_diameter_km)||Number(SOLAR[id]?.physical_diameter_km)||0,dia=apparentDiameterDeg(diam,po.distanceKm||0),minPx=Number(PINFO[id]?.rendering?.minimum_display_px)||1;drawSizedEllipse(ctx,p,dia,dia,s,w,h,dpr,PLANET_COLORS[id]||"#d7bea0",plA,minPx,.86)}if(plnA>0){ctx.globalAlpha=plnA;ctx.fillStyle=PLANET_LABEL_COLORS[id]||"#ead2b6";ctx.font=`${8*(display.objectTextScale||4)*dpr}px ${fontFamily}`;ctx.textAlign="left";skyText(ctx,s,w,h,p,nm,5*dpr,-4*dpr)}ctx.globalAlpha=1}}
 const coA=fade("global:smallBodies",!!s.global.smallBodies),conA=fade("global:cometNames",!!s.global.cometNames);if(coA>0||conA>0){for(const c of cometPositions(s)){const p=point(c,s,w,h);if(!p)continue;if(coA>0){ctx.globalAlpha=coA;ctx.strokeStyle="#79e6aa";ctx.beginPath();ctx.arc(p.x,p.y,4*dpr,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(p.x+3*dpr,p.y-3*dpr);ctx.lineTo(p.x+9*dpr,p.y-9*dpr);ctx.stroke()}if(conA>0){ctx.globalAlpha=conA;ctx.fillStyle="#99f2bc";ctx.font=`${8*(display.objectTextScale||4)*dpr}px ${fontFamily}`;ctx.textAlign="left";skyText(ctx,s,w,h,p,c.name||c.designation||"彗星",6*dpr,-5*dpr)}ctx.globalAlpha=1}}
 const meA=fade("global:meteors",!!s.global.meteors),menA=fade("global:meteorNames",!!s.global.meteorNames);if(meA>0||menA>0){for(const m of METEORS.filter(x=>meteorActive(x,s.time))){const p=point(m,s,w,h);if(!p)continue;if(meA>0){ctx.globalAlpha=meA;ctx.strokeStyle="#ffad69";ctx.beginPath();ctx.arc(p.x,p.y,6*dpr,0,Math.PI*2);ctx.stroke();for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+12*dpr*Math.cos(a),p.y+12*dpr*Math.sin(a));ctx.stroke()}}if(menA>0){ctx.globalAlpha=menA;ctx.fillStyle="#ffc18e";ctx.font=`${8*(display.objectTextScale||4)*dpr}px ${fontFamily}`;ctx.textAlign="left";skyText(ctx,s,w,h,p,m.name||m.code||"流星群",8*dpr,-7*dpr)}ctx.globalAlpha=1}}
 if(!opts.gpuSkyLayer)drawMeteorEvents(ctx,s,w,h,dpr);
 const marked=new Set([...Object.keys(s.highlights||{}),...Object.keys(s.labels||{})]);for(const id of marked){const ha=fade("highlight:"+id,!!s.highlights[id]),la=fade("label:"+id,!!s.labels[id]);if(ha<=0&&la<=0)continue;const pos=targetPosition(id,s.time),p=pos?point(pos,s,w,h):null;if(!p)continue;const obj=D.stars.find(x=>x.id===id)||D.dsos.find(x=>x.id===id)||D.planetsInfo.find(x=>x.id===id)||C[id]||STAR[id]||(id==="Sun"?{name:"太陽"}:id==="Moon"?{name:"月"}:null),nm=obj?.display_name||obj?.name||PLANET_NAMES[id]||id;if(ha>0){ctx.globalAlpha=ha;ctx.strokeStyle="#ffd65c";ctx.lineWidth=2*dpr;ctx.beginPath();ctx.arc(p.x,p.y,10*dpr,0,Math.PI*2);ctx.stroke()}if(la>0){ctx.globalAlpha=la;ctx.fillStyle="#fff";ctx.font=`${9*(display.objectTextScale||4)*dpr}px ${fontFamily}`;ctx.textAlign="center";skyText(ctx,s,w,h,p,nm,0,-(8+3*(display.objectTextScale||4))*dpr)}ctx.globalAlpha=1}
 ctx.restore();if(all){ctx.strokeStyle="rgba(120,190,175,.8)";ctx.lineWidth=1.4*dpr;ctx.beginPath();ctx.arc(w/2,h/2,rad,0,Math.PI*2);ctx.stroke()}else drawGround(ctx,s,w,h,dpr);drawCompass(ctx,s,w,h,dpr,display,fontFamily);
 if(drawAnn){if(all){ctx.save();ctx.beginPath();ctx.arc(w/2,h/2,rad,0,Math.PI*2);ctx.clip()}drawAnnotations(ctx,[...(s.annotations||[]),...(s.draftAnnotation?[s.draftAnnotation]:[])],w,h,s);if(all)ctx.restore()}
}
window.Astrorium={D,C,S,O,PINFO,SOLAR,ASTERISMS,STAR,ART,makeState,revive,serial,command,ensureC,effectiveConst,effectiveAst,render,visibleConstellations,visibleAsterisms,loadLines,loadOnlineStars,importStarCatalogText,loadMilkyWay,loadComets,loadMeteors,activeMeteorShowers,dir16,altaz,targetById,targetPosition,centerOn,drawAnnotations,screenToRaDec,sunsetForDate,calcSkyInfo,moonPhaseInfo,planet,PLANET_NAMES,PLANET_COLORS,bvLabel,fetchTimed,effectiveStarMagLimit,sun,moon,point,coordFor,constellationSegments,originalConstellationSegments,customConstellationCenter,onlineStars,lineStars,userStars,milkyClouds:()=>buildMilkyWayClouds(),registerUserStars,registerConstellationStarMap,apparentDiameterDeg,angularDiameterPx,invalidateArtMesh,applyArtConfig,applyArtOverrides,setArtImageOverride,artImage,artSkyPoint,naturalDsoObjects};
})();