(()=>{"use strict";
let CAP_CACHE=null;
function releaseContext(gl){try{gl&&gl.getExtension&&gl.getExtension("WEBGL_lose_context")?.loseContext()}catch(_){}}
function detectCapabilities(){if(CAP_CACHE)return{...CAP_CACHE};let webgl2=false,webgl=false;try{const c=document.createElement("canvas");let gl=c.getContext("webgl2",{alpha:true,antialias:false,depth:false,stencil:false});if(gl){webgl2=true;webgl=true;releaseContext(gl)}else{gl=c.getContext("webgl",{alpha:true,antialias:false,depth:false,stencil:false})||c.getContext("experimental-webgl",{alpha:true,antialias:false,depth:false,stencil:false});if(gl){webgl=true;releaseContext(gl)}}}catch(_){}CAP_CACHE={canvas2d:true,webgl,webgl2,webgpu:!!navigator.gpu};return{...CAP_CACHE}}
class CanvasRenderer{constructor(canvas,A){this.canvas=canvas;this.A=A;this.backend="canvas2d";this.frames=0;this.lastCostMs=0}render(state,options={}){const t=performance.now();this.A.render(this.canvas,state,true,options);this.lastCostMs=performance.now()-t;this.frames++;return this.lastCostMs}resize(){}dispose(){}diagnostics(){return{backend:this.backend,frames:this.frames,lastCostMs:+this.lastCostMs.toFixed(2),backing:[this.canvas.width,this.canvas.height],css:[this.canvas.clientWidth,this.canvas.clientHeight]}}}
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||"shader compile failed");return s}
function program(gl,vs,fs){const p=gl.createProgram(),v=shader(gl,gl.VERTEX_SHADER,vs),f=shader(gl,gl.FRAGMENT_SHADER,fs);gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||"program link failed");try{gl.deleteShader(v);gl.deleteShader(f)}catch(_){}return p}
function hexRgb(h){const m=String(h||"").match(/^#?([0-9a-f]{6})$/i);if(!m)return null;const n=parseInt(m[1],16);return[((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255]}
function bvRgb(bv){bv=Number(bv);if(!Number.isFinite(bv))return[.96,.97,1];const t=4600*(1/(.92*bv+1.7)+1/(.92*bv+.62))/100;let r,g,b;if(t<=66){r=255;g=99.4708025861*Math.log(t)-161.1195681661;b=t<=19?0:138.5177312231*Math.log(t-10)-305.0447927307}else{r=329.698727446*Math.pow(t-60,-.1332047592);g=288.1221695283*Math.pow(t-60,-.0755148492);b=255}const cl=v=>Math.max(0,Math.min(255,v))/255;return[cl(r),cl(g),cl(b)]}
function starRgb(st){return hexRgb(st?.display_color_hex)||bvRgb(st?.bv)}
function jd(d){return d.getTime()/864e5+2440587.5}function norm(v){return((v%360)+360)%360}function gmst(j){const T=(j-2451545)/36525;return norm(280.46061837+360.98564736629*(j-2451545)+.000387933*T*T-T*T*T/38710000)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function smooth01(t){t=clamp(t,0,1);return t*t*(3-2*t)}
const NATURAL_EXTRA=[
 {id:"LMC",name:"大マゼラン雲",ra:80.8942,dec:-69.7561,mag:.9,type:"galaxy",major:10.5,minor:8.0,col:[.76,.82,.86]},
 {id:"SMC",name:"小マゼラン雲",ra:13.1867,dec:-72.8286,mag:2.7,type:"galaxy",major:5.2,minor:3.2,col:[.76,.82,.86]},
 {id:"NGC5139",name:"ω星団",ra:201.697,dec:-47.4795,mag:3.7,type:"cluster",major:.60,minor:.60,col:[.90,.88,.78]},
 {id:"NGC104",name:"47 Tuc",ra:6.0236,dec:-72.0813,mag:4.1,type:"cluster",major:.52,minor:.52,col:[.90,.88,.78]}
];
function dsoName(o){return typeof o?.name==="object"?(o.name.ja||o.name.en||o.id):(o?.display_name||o?.name||o?.id||"")}
function dsoPos(o){const p=o?.position;return p&&Number.isFinite(Number(p.ra_deg))?{ra:+p.ra_deg,dec:+p.dec_deg}:{ra:+o.ra,dec:+o.dec}}
function dsoVisuals(A){const out=[];for(const o of A.D?.dsos||[]){const mag=Number(o.magnitude_v??o.mag);if(!Number.isFinite(mag)||mag>6.25)continue;const p=dsoPos(o);if(!Number.isFinite(p.ra)||!Number.isFinite(p.dec))continue;const a=o.angular_size||{},maj=Number(a.major_arcmin)/60,min=Number(a.minor_arcmin)/60;if(!(maj>0))continue;out.push({id:o.id,name:dsoName(o),ra:p.ra,dec:p.dec,mag,type:o.type||"dso",major:maj,minor:min>0?min:maj,col:o.type==="nebula"?[.66,.82,.72]:o.type==="galaxy"?[.80,.82,.78]:[.88,.88,.80]})}return out.concat(NATURAL_EXTRA)}

class SharedSkyGPU{
 constructor(main,A){this.main=main;this.A=A;this.canvas=document.createElement("canvas");this.frames=0;this.lastCostMs=0;this.ready=false;this.contextLost=false;this.lastError="";this.starCount=0;this.artTextures=new Map();this.artFade=new Map();this.dsoData=dsoVisuals(A);this.ctxOpts={alpha:true,antialias:false,premultipliedAlpha:true,preserveDrawingBuffer:true,depth:false,stencil:false,powerPreference:"high-performance"};this.gl=this.canvas.getContext("webgl",this.ctxOpts)||this.canvas.getContext("experimental-webgl",this.ctxOpts);if(!this.gl)throw new Error("WebGL unavailable");this.canvas.addEventListener?.("webglcontextlost",e=>{try{e.preventDefault()}catch(_){}this.contextLost=true;this.ready=false;this.lastError="webglcontextlost"});this.canvas.addEventListener?.("webglcontextrestored",()=>{this.contextLost=false;try{this.initGL();this.lastError=""}catch(e){this.ready=false;this.lastError=String(e?.message||e)}});this.initGL()}
 initGL(){const gl=this.gl;
  this.starP=program(gl,`attribute vec4 a0;attribute vec3 a1;uniform vec2 u_res;uniform float u_lst,u_lat,u_camAz,u_camAlt,u_fov,u_all,u_scale,u_magLim,u_alpha,u_brightness;varying vec4 v_col;const float PI=3.141592653589793;void main(){float ra=a0.x,dec=a0.y,mag=a0.z;float H=u_lst-ra;float sd=sin(dec),cd=cos(dec),sl=sin(u_lat),cl=cos(u_lat),ch=cos(H),sh=sin(H);float up=sd*sl+cd*cl*ch;float alt=asin(clamp(up,-1.0,1.0));float east=-cd*sh;float north=sd*cl-cd*sl*ch;float az=atan(east,north);if(az<0.0)az+=2.0*PI;vec2 pix;float visible=1.0;if(u_all>0.5){if(alt<0.0)visible=0.0;float rad=min(u_res.x,u_res.y)*.47;float rr=(PI*.5-alt)/(PI*.5)*rad;pix=vec2(u_res.x*.5-rr*sin(az),u_res.y*.5-rr*cos(az));}else{float da=az-u_camAz;if(da>PI)da-=2.0*PI;if(da<-PI)da+=2.0*PI;float ca=u_camAlt;float x=cos(alt)*sin(da);float y=sin(alt)*cos(ca)-cos(alt)*cos(da)*sin(ca);float z=sin(alt)*sin(ca)+cos(alt)*cos(da)*cos(ca);if(z<=.015)visible=0.0;float f=(u_res.x*.5)/tan(u_fov*.5);pix=vec2(u_res.x*.5+f*x/max(z,.015),u_res.y*.5-f*y/max(z,.015));}if(mag>u_magLim)visible=0.0;vec2 clip=vec2(pix.x/u_res.x*2.0-1.0,1.0-pix.y/u_res.y*2.0);gl_Position=vec4(clip,0.0,1.0);float flux=pow(2.512,-0.20*(mag+1.0));float b=clamp(flux,.028,1.0);gl_PointSize=max(1.0,(0.45+3.8*pow(b,.65))*u_scale)*visible;v_col=vec4(a1,min(1.0,(0.04+0.96*pow(b,.70))*u_alpha*u_brightness)*visible);}`,`precision mediump float;varying vec4 v_col;void main(){vec2 q=gl_PointCoord-.5;float r=length(q);if(r>.5)discard;float core=exp(-r*r*34.0);float halo=exp(-r*r*9.0)*.32;float a=clamp((core+halo)*v_col.a,0.0,1.0);gl_FragColor=vec4(v_col.rgb,a);}`);
  this.starB0=gl.createBuffer();this.starB1=gl.createBuffer();this.starU={};for(const n of["u_res","u_lst","u_lat","u_camAz","u_camAlt","u_fov","u_all","u_scale","u_magLim","u_alpha","u_brightness"])this.starU[n]=gl.getUniformLocation(this.starP,n);this.starA0=gl.getAttribLocation(this.starP,"a0");this.starA1=gl.getAttribLocation(this.starP,"a1");
  this.spriteP=program(gl,`attribute vec2 a_pos;attribute float a_size;attribute vec4 a_col;attribute vec2 a_shape;uniform vec2 u_res;varying vec4 v_col;varying vec2 v_shape;void main(){vec2 clip=vec2(a_pos.x/u_res.x*2.0-1.0,1.0-a_pos.y/u_res.y*2.0);gl_Position=vec4(clip,0,1);gl_PointSize=a_size;v_col=a_col;v_shape=a_shape;}`,`precision mediump float;varying vec4 v_col;varying vec2 v_shape;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}void main(){vec2 uv=gl_PointCoord;vec2 q=(uv-.5)*2.0;q.y/=max(.08,v_shape.x);float r2=dot(q,q);if(r2>1.0)discard;float k=v_shape.y;float a=0.0;if(k<.35){float broad=exp(-r2*2.0);float filament=.72+.28*sin((q.x*8.0+q.y*5.0)+sin(q.y*11.0)*1.7);float grain=.80+.20*hash(floor(uv*28.0));float lane=1.0-.34*exp(-pow(q.y*.78+sin(q.x*5.5)*.12,2.0)*36.0);a=v_col.a*broad*filament*grain*lane;}else if(k<.65){float core=exp(-r2*11.0);float disk=exp(-r2*2.4);float dust=1.0-.28*exp(-pow(q.y+.10*sin(q.x*7.0),2.0)*55.0);a=v_col.a*(.72*disk*dust+.60*core);}else if(k<1.5){float soft=exp(-r2*2.3);float knots=.68+.32*sin(q.x*10.0+sin(q.y*9.0)*2.0)*sin(q.y*8.0);float wisps=.78+.22*hash(floor((uv+vec2(uv.y,uv.x))*20.0));a=v_col.a*soft*clamp(knots,0.25,1.0)*wisps;}else{float soft=exp(-r2*3.1);float n=hash(floor(uv*26.0));float stars=.20+1.55*step(.82,n);float core=.35*exp(-r2*10.0);a=v_col.a*(soft*stars+core);}gl_FragColor=vec4(v_col.rgb,clamp(a,0.0,1.0));}`);this.spriteBuf=gl.createBuffer();this.spriteUres=gl.getUniformLocation(this.spriteP,"u_res");this.spriteAttrs={pos:gl.getAttribLocation(this.spriteP,"a_pos"),size:gl.getAttribLocation(this.spriteP,"a_size"),col:gl.getAttribLocation(this.spriteP,"a_col"),shape:gl.getAttribLocation(this.spriteP,"a_shape")};
  this.atmosP=program(gl,`attribute vec2 a_pos;varying vec2 v_uv;void main(){v_uv=a_pos*.5+.5;gl_Position=vec4(a_pos,0,1);}`,`precision mediump float;varying vec2 v_uv;uniform vec2 u_res,u_sun,u_moon;uniform float u_day,u_moonA;void main(){vec2 p=vec2(v_uv.x,1.0-v_uv.y)*u_res;float ds=distance(p,u_sun)/max(u_res.x,u_res.y);float dm=distance(p,u_moon)/max(u_res.x,u_res.y);float sa=exp(-ds*ds*8.5)*u_day;float ma=exp(-dm*dm*13.0)*u_moonA;vec3 c=vec3(1.0,.72,.42)*sa*.18+vec3(.62,.72,.90)*ma*.14;gl_FragColor=vec4(c,clamp(sa*.38+ma*.30,0.0,.45));}`);this.quadBuf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.quadBuf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);this.atmosA=gl.getAttribLocation(this.atmosP,"a_pos");this.atmosU={res:gl.getUniformLocation(this.atmosP,"u_res"),sun:gl.getUniformLocation(this.atmosP,"u_sun"),moon:gl.getUniformLocation(this.atmosP,"u_moon"),day:gl.getUniformLocation(this.atmosP,"u_day"),moonA:gl.getUniformLocation(this.atmosP,"u_moonA")};
  this.texP=program(gl,`attribute vec2 a_pos;attribute vec2 a_uv;varying vec2 v_uv;void main(){gl_Position=vec4(a_pos,0,1);v_uv=a_uv;}`,`precision mediump float;varying vec2 v_uv;uniform sampler2D u_tex;uniform float u_alpha;void main(){vec4 c=texture2D(u_tex,v_uv);gl_FragColor=vec4(c.rgb,c.a*u_alpha);}`);this.texBuf=gl.createBuffer();this.texApos=gl.getAttribLocation(this.texP,"a_pos");this.texAuv=gl.getAttribLocation(this.texP,"a_uv");this.texUalpha=gl.getUniformLocation(this.texP,"u_alpha");
  this.lineP=program(gl,`attribute vec2 a_pos;attribute vec4 a_col;varying vec4 v_col;void main(){gl_Position=vec4(a_pos,0,1);v_col=a_col;}`,`precision mediump float;varying vec4 v_col;void main(){gl_FragColor=v_col;}`);this.lineBuf=gl.createBuffer();this.lineApos=gl.getAttribLocation(this.lineP,"a_pos");this.lineAcol=gl.getAttribLocation(this.lineP,"a_col");
  gl.disable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);this.sig="";this.ready=true;this.rebuildStars();
 }
 resize(options={}){const r=this.main.getBoundingClientRect(),nativeDpr=Math.max(1,Math.min(2,devicePixelRatio||1));let dpr;if(Number.isFinite(Number(options.dprScale))){const scale=clamp(Number(options.dprScale),.5,1);dpr=Math.max(1,nativeDpr*scale)}else{const cap=Number.isFinite(Number(options.dprCap))?Math.max(.45,+options.dprCap):2;dpr=Math.max(.45,Math.min(cap,devicePixelRatio||1))}const w=Math.max(240,Math.round(r.width*dpr)),h=Math.max(135,Math.round(r.height*dpr));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}this.gl.viewport(0,0,w,h);return{w,h,dpr}}
 clear(){const gl=this.gl;gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT)}
 rebuildStars(){if(!this.ready||this.contextLost||this.gl.isContextLost?.())return false;const A=this.A,online=A.onlineStars?.()||[],base=online.length?online:(A.D.stars||[]),extra=A.userStars?.()||[],seen=new Set(base.map(x=>String(x.id||""))),arr=extra.length?[...base,...extra.filter(x=>!seen.has(String(x.id||"")))]:base,sig=arr.length+":"+(arr[0]?.id||"")+":"+(arr[arr.length-1]?.id||"");if(sig===this.sig)return this.starCount>0;this.sig=sig;const a0=new Float32Array(arr.length*4),a1=new Float32Array(arr.length*3);for(let i=0;i<arr.length;i++){const s=arr[i],o=i*4,c=i*3,r=starRgb(s);a0[o]=(Number(s.ra)||0)*Math.PI/180;a0[o+1]=(Number(s.dec)||0)*Math.PI/180;a0[o+2]=Number.isFinite(Number(s.mag))?Number(s.mag):8;a1[c]=r[0];a1[c+1]=r[1];a1[c+2]=r[2]}const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,this.starB0);gl.bufferData(gl.ARRAY_BUFFER,a0,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,this.starB1);gl.bufferData(gl.ARRAY_BUFFER,a1,gl.STATIC_DRAW);this.starCount=arr.length;return this.starCount>0}
 drawAtmos(state,w,h){const A=this.A,gl=this.gl,date=state.time instanceof Date?state.time:new Date(state.time),su=A.sun(jd(date)),sua=A.altaz(su.ra,su.dec,date,+state.location.lat,+state.location.lon),mo=A.moon(jd(date)),moa=A.altaz(mo.ra,mo.dec,date,+state.location.lat,+state.location.lon),sp=A.point(su,state,w,h),mp=A.point(mo,state,w,h),day=state.global?.daylight?smooth01((sua.alt+18)/30):0,moonA=state.global?.moonlight?smooth01((moa.alt+2)/15)*smooth01((-sua.alt-2)/12):0;if(day<.002&&moonA<.002)return;gl.useProgram(this.atmosP);gl.bindBuffer(gl.ARRAY_BUFFER,this.quadBuf);gl.enableVertexAttribArray(this.atmosA);gl.vertexAttribPointer(this.atmosA,2,gl.FLOAT,false,0,0);gl.uniform2f(this.atmosU.res,w,h);gl.uniform2f(this.atmosU.sun,sp?.x??-9999,sp?.y??-9999);gl.uniform2f(this.atmosU.moon,mp?.x??-9999,mp?.y??-9999);gl.uniform1f(this.atmosU.day,day);gl.uniform1f(this.atmosU.moonA,moonA);gl.drawArrays(gl.TRIANGLES,0,6)}
 drawSprites(rows,w,h){if(!rows.length)return;const gl=this.gl,a=new Float32Array(rows.length*9);for(let i=0;i<rows.length;i++){const r=rows[i],o=i*9;a[o]=r.x;a[o+1]=r.y;a[o+2]=r.size;a[o+3]=r.col[0];a[o+4]=r.col[1];a[o+5]=r.col[2];a[o+6]=r.alpha;a[o+7]=r.aspect??1;a[o+8]=r.kind??0}gl.useProgram(this.spriteP);gl.uniform2f(this.spriteUres,w,h);gl.bindBuffer(gl.ARRAY_BUFFER,this.spriteBuf);gl.bufferData(gl.ARRAY_BUFFER,a,gl.DYNAMIC_DRAW);const stride=9*4;gl.enableVertexAttribArray(this.spriteAttrs.pos);gl.vertexAttribPointer(this.spriteAttrs.pos,2,gl.FLOAT,false,stride,0);gl.enableVertexAttribArray(this.spriteAttrs.size);gl.vertexAttribPointer(this.spriteAttrs.size,1,gl.FLOAT,false,stride,2*4);gl.enableVertexAttribArray(this.spriteAttrs.col);gl.vertexAttribPointer(this.spriteAttrs.col,4,gl.FLOAT,false,stride,3*4);gl.enableVertexAttribArray(this.spriteAttrs.shape);gl.vertexAttribPointer(this.spriteAttrs.shape,2,gl.FLOAT,false,stride,7*4);gl.drawArrays(gl.POINTS,0,rows.length)}
 drawMilky(state,w,h){if(!state.global?.milkyWay)return;const A=this.A,date=state.time instanceof Date?state.time:new Date(state.time),su=A.sun(jd(date)),sua=A.altaz(su.ra,su.dec,date,+state.location.lat,+state.location.lon),night=smooth01(clamp((-sua.alt-4)/12,0,1)),bright=clamp(Number(state.display?.milkyWayBrightness)||1,.25,2);if(night<.01)return;const rows=[];for(const q of A.milkyClouds?.()||[]){const p=A.point(q,state,w,h);if(!p)continue;const sz=Math.max(8,A.angularDiameterPx?.(q.size,state,w,h)||20),base=clamp(q.a*bright*night,0,.19);rows.push({x:p.x,y:p.y,size:Math.min(sz*1.45,760),col:[.72,.77,.76],alpha:base*.42,aspect:1,kind:.18});rows.push({x:p.x,y:p.y,size:Math.min(sz*.92,560),col:[.86,.84,.76],alpha:base*.72,aspect:.78,kind:.22})}this.drawSprites(rows,w,h)}
 drawStars(state,w,h,dpr){if(!state.global?.stars||!this.rebuildStars())return;const A=this.A,gl=this.gl,date=state.time instanceof Date?state.time:new Date(state.time),lst=(gmst(jd(date))+Number(state.location?.lon||0))*Math.PI/180,lat=Number(state.location?.lat||0)*Math.PI/180,su=A.sun(jd(date)),sua=A.altaz(su.ra,su.dec,date,+state.location.lat,+state.location.lon),alpha=state.global?.daylight?Math.max(0,Math.min(1,(-sua.alt-2)/10)):1;gl.useProgram(this.starP);gl.uniform2f(this.starU.u_res,w,h);gl.uniform1f(this.starU.u_lst,lst);gl.uniform1f(this.starU.u_lat,lat);gl.uniform1f(this.starU.u_camAz,Number(state.camera?.az||0)*Math.PI/180);gl.uniform1f(this.starU.u_camAlt,Number(state.camera?.alt||0)*Math.PI/180);gl.uniform1f(this.starU.u_fov,Number(state.camera?.fov||120)*Math.PI/180);gl.uniform1f(this.starU.u_all,state.projection==="allsky"?1:0);gl.uniform1f(this.starU.u_scale,Math.max(.5,Number(state.display?.starScale)||5)*dpr*.34);gl.uniform1f(this.starU.u_magLim,A.effectiveStarMagLimit?A.effectiveStarMagLimit(state):(Number(state.global?.mag)||6));gl.uniform1f(this.starU.u_alpha,alpha);gl.uniform1f(this.starU.u_brightness,clamp(Number(state.display?.starBrightness)||1,.25,2.5));gl.bindBuffer(gl.ARRAY_BUFFER,this.starB0);gl.enableVertexAttribArray(this.starA0);gl.vertexAttribPointer(this.starA0,4,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,this.starB1);gl.enableVertexAttribArray(this.starA1);gl.vertexAttribPointer(this.starA1,3,gl.FLOAT,false,0,0);gl.drawArrays(gl.POINTS,0,this.starCount)}
 drawNaturalDSO(state,w,h){if(state.global?.naturalDeepSky===false)return;const A=this.A,date=state.time instanceof Date?state.time:new Date(state.time),su=A.sun(jd(date)),sua=A.altaz(su.ra,su.dec,date,+state.location.lat,+state.location.lon),night=smooth01(clamp((-sua.alt-5)/12,0,1));if(night<.01)return;const rows=[];for(const o of this.dsoData){const p=A.point(o,state,w,h);if(!p)continue;const maj=Math.max(2,A.angularDiameterPx?.(o.major,state,w,h)||4),min=Math.max(1,A.angularDiameterPx?.(o.minor,state,w,h)||maj),surface=Math.max(.08,Math.min(1,Math.pow(10,-.12*(o.mag-2.5)))),alpha=clamp(.035+.19*surface,0,.27)*night;let kind=.48;if(o.type==="cluster"||o.type==="star_cloud")kind=2.0;else if(o.type==="nebula")kind=.9;const size=Math.min(Math.max(maj,min),1000),aspect=clamp(min/maj,.07,1);rows.push({x:p.x,y:p.y,size,col:o.col,alpha,aspect,kind});if(kind<.65&&size>16)rows.push({x:p.x,y:p.y,size:size*.38,col:[Math.min(1,o.col[0]*1.08),Math.min(1,o.col[1]*1.08),Math.min(1,o.col[2]*1.06)],alpha:alpha*.65,aspect:Math.min(1,aspect*1.35),kind:.50})}this.drawSprites(rows,w,h)}
 textureFor(id,im){const gl=this.gl,src=im?.__nicoleSrc||im?.src||"",old=this.artTextures.get(id);if(old&&old.src===src&&old.w===im.naturalWidth&&old.h===im.naturalHeight)return old.tex;if(old?.tex)try{gl.deleteTexture(old.tex)}catch(_){}const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,true);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,im);this.artTextures.set(id,{tex,src,w:im.naturalWidth,h:im.naturalHeight});return tex}
 artEntries(state){const now=performance.now(),out=[];for(const c of this.A.D?.constellations||[]){if(!this.A.ART?.[c.id])continue;const on=!!this.A.effectiveConst?.(state,c.id,"art");let f=this.artFade.get(c.id);if(!f){f={a:on?0:0,t:now};this.artFade.set(c.id,f)}const dt=Math.min(60,Math.max(0,now-f.t));f.t=now;f.a=clamp(f.a+(on?1:-1)*dt/420,0,1);if(f.a>.001||on)out.push({id:c.id,alpha:f.a})}return out}
 artsReady(state,entries=null){for(const e of(entries||this.artEntries(state))){const im=this.A.artImage?.(e.id);if(!im||!im.complete||!im.naturalWidth)return false}return true}
 drawArts(state,w,h){const A=this.A,entries=this.artEntries(state);if(!entries.length)return true;if(!this.artsReady(state,entries))return false;const gl=this.gl;gl.useProgram(this.texP);for(const ent of entries){const id=ent.id,def=A.ART[id],im=A.artImage(id);if(!def||!im)continue;const count=entries.length,n=count<=10?5:count<=30?4:3,m=n,verts=[];for(let j=0;j<m;j++)for(let i=0;i<n;i++){const u0=i/n,u1=(i+1)/n,v0=j/m,v1=(j+1)/m,qs=[[u0,v0],[u1,v0],[u0,v1],[u1,v1]].map(([u,v])=>A.artSkyPoint(def,u,v)),ps=qs.map(q=>A.point(q,state,w,h));if(ps.some(p=>!p))continue;const cv=p=>[p.x/w*2-1,1-p.y/h*2],p0=cv(ps[0]),p1=cv(ps[1]),p2=cv(ps[2]),p3=cv(ps[3]);verts.push(...p0,u0,v0,...p1,u1,v0,...p2,u0,v1,...p1,u1,v0,...p3,u1,v1,...p2,u0,v1)}if(!verts.length)continue;const tex=this.textureFor(id,im),arr=new Float32Array(verts);gl.bindTexture(gl.TEXTURE_2D,tex);gl.bindBuffer(gl.ARRAY_BUFFER,this.texBuf);gl.bufferData(gl.ARRAY_BUFFER,arr,gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(this.texApos);gl.vertexAttribPointer(this.texApos,2,gl.FLOAT,false,4*4,0);gl.enableVertexAttribArray(this.texAuv);gl.vertexAttribPointer(this.texAuv,2,gl.FLOAT,false,4*4,2*4);gl.uniform1f(this.texUalpha,clamp((Number(def.opacity)||.58)*ent.alpha,0,1));gl.drawArrays(gl.TRIANGLES,0,arr.length/4)}return true}
 drawMeteors(state,w,h){const evs=state.meteorEvents||[];if(!evs.length)return;const A=this.A,now=Date.now(),verts=[];for(const ev of evs){const dur=Math.max(180,Number(ev.duration)||650),t=(now-Number(ev.born||0))/dur;if(t<0||t>1.45)continue;const a=A.point(ev.p1,state,w,h),b=A.point(ev.p2,state,w,h);if(!a||!b)continue;const u=clamp(t,0,1),ease=1-Math.pow(1-u,2.35),hx=a.x+(b.x-a.x)*ease,hy=a.y+(b.y-a.y)*ease,dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,nx=dx/len,ny=dy/len,bright=clamp(Number(ev.brightness)||1,.25,2.4),tail=Math.min(len,55+130*bright)*(.42+.58*u),tx=hx-nx*tail,ty=hy-ny*tail,px=-ny*(.7+bright),py=nx*(.7+bright),life=t<=1?Math.min(1,t*10):Math.max(0,1-(t-1)/.45),rgb=(Array.isArray(ev.rgb)?ev.rgb:[235,245,255]).map(v=>v/255),c0=[rgb[0],rgb[1],rgb[2],0],c1=[Math.min(1,rgb[0]*1.1),Math.min(1,rgb[1]*1.1),1,clamp(.5*bright*life,0,1)],clip=(x,y)=>[x/w*2-1,1-y/h*2],vs=[[tx+px,ty+py,c0],[tx-px,ty-py,c0],[hx+px,hy+py,c1],[hx+px,hy+py,c1],[tx-px,ty-py,c0],[hx-px,hy-py,c1]];for(const v of vs){const p=clip(v[0],v[1]);verts.push(p[0],p[1],...v[2])}}if(!verts.length)return;const gl=this.gl,arr=new Float32Array(verts);gl.useProgram(this.lineP);gl.bindBuffer(gl.ARRAY_BUFFER,this.lineBuf);gl.bufferData(gl.ARRAY_BUFFER,arr,gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(this.lineApos);gl.vertexAttribPointer(this.lineApos,2,gl.FLOAT,false,6*4,0);gl.enableVertexAttribArray(this.lineAcol);gl.vertexAttribPointer(this.lineAcol,4,gl.FLOAT,false,6*4,2*4);gl.drawArrays(gl.TRIANGLES,0,arr.length/6)}
 render(state,options={}){const t=performance.now(),gl=this.gl;try{if(this.contextLost||gl.isContextLost?.()||!this.ready)return null;const{w,h,dpr}=this.resize(options);this.clear();gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);this.drawAtmos(state,w,h);this.drawMilky(state,w,h);this.drawNaturalDSO(state,w,h);this.drawStars(state,w,h,dpr);const artsReady=this.drawArts(state,w,h);this.drawMeteors(state,w,h);gl.flush();if((this.frames%60)===0){const e=gl.getError();if(e!==gl.NO_ERROR)throw new Error(`WebGL error ${e}`)}this.frames++;this.lastCostMs=performance.now()-t;this.lastError="";return{canvas:this.canvas,artsReady}}catch(e){this.lastError=String(e?.message||e);this.lastCostMs=performance.now()-t;return null}}
 dispose(){for(const v of this.artTextures.values())try{this.gl.deleteTexture(v.tex)}catch(_){}this.artTextures.clear();releaseContext(this.gl);this.ready=false}
 diagnostics(){return{backend:"webgl-shared-sky-v2",ready:this.ready&&!this.contextLost,frames:this.frames,lastCostMs:+this.lastCostMs.toFixed(2),starCount:this.starCount,naturalDSO:this.dsoData.length,artTextures:this.artTextures.size,lastError:this.lastError,backing:[this.canvas.width,this.canvas.height]}}
}
class HybridRenderer{constructor(canvas,A){this.canvas=canvas;this.A=A;this.backend="hybrid-shared-webgl-v2+canvas2d";this.frames=0;this.lastCostMs=0;this.fallbackFrames=0;this.gpu=null;this.lastError="";try{this.gpu=new SharedSkyGPU(canvas,A)}catch(e){this.lastError=String(e?.message||e);console.warn("Shared GPU renderer unavailable; Canvas fallback",e)}}render(state,options={}){const t=performance.now(),g=this.gpu?.render(state,options)||null;if(!g)this.fallbackFrames++;const ropts={...options};if(g){ropts.gpuSkyLayer=g.canvas;ropts.gpuArtsReady=!!g.artsReady}this.A.render(this.canvas,state,true,ropts);this.lastCostMs=performance.now()-t;this.frames++;return this.lastCostMs}dispose(){this.gpu?.dispose?.()}resize(){}diagnostics(){return{backend:this.backend,frames:this.frames,fallbackFrames:this.fallbackFrames,lastCostMs:+this.lastCostMs.toFixed(2),gpu:this.gpu?.diagnostics?.()||null,lastError:this.lastError,backing:[this.canvas.width,this.canvas.height],css:[this.canvas.clientWidth,this.canvas.clientHeight]}}}
function createRenderer(canvas,A,options={}){const caps=detectCapabilities();if(options.backend!=="canvas2d"&&caps.webgl){try{return new HybridRenderer(canvas,A)}catch(e){console.warn("Hybrid renderer fallback",e)}}return new CanvasRenderer(canvas,A)}
window.AstroriumRenderer={createRenderer,detectCapabilities,CanvasRenderer,HybridRenderer,SharedSkyGPU};
})();
